// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearUserTelegramChatID = `-- name: ClearUserTelegramChatID :exec
UPDATE users SET telegram_chat_id = NULL WHERE telegram_chat_id = $1
`

func (q *Queries) ClearUserTelegramChatID(ctx context.Context, telegramChatID *int64) error {
	_, err := q.db.Exec(ctx, clearUserTelegramChatID, telegramChatID)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, tenant_id, csrf_hash, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	TenantID  uuid.UUID
	CsrfHash  []byte
	UserAgent string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.TenantID,
		arg.CsrfHash,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	return err
}

const createTelegramLinkCode = `-- name: CreateTelegramLinkCode :exec
INSERT INTO telegram_link_codes (code, tenant_id, user_id, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateTelegramLinkCodeParams struct {
	Code      string
	TenantID  uuid.UUID
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateTelegramLinkCode(ctx context.Context, arg CreateTelegramLinkCodeParams) error {
	_, err := q.db.Exec(ctx, createTelegramLinkCode,
		arg.Code,
		arg.TenantID,
		arg.UserID,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, tenant_id, email, password_hash, name, role)
VALUES ($1, $2, lower($3), $4, $5, $6)
RETURNING id, tenant_id, email, password_hash, name, role, telegram_chat_id, created_at
`

type CreateUserParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Lower        string
	PasswordHash string
	Name         string
	Role         UserRole
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.TenantID,
		arg.Lower,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.TelegramChatID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredTelegramLinkCodes = `-- name: DeleteExpiredTelegramLinkCodes :execrows
DELETE FROM telegram_link_codes WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredTelegramLinkCodes(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredTelegramLinkCodes, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT
    s.token_hash,
    s.csrf_hash,
    s.expires_at,
    s.last_seen_at,
    u.id         AS user_id,
    u.tenant_id,
    u.email,
    u.name,
    u.role,
    u.telegram_chat_id,
    t.name       AS tenant_name,
    t.timezone,
    t.is_sandbox,
    t.clock_offset,
    t.settings,
    t.autopilot,
    t.seed,
    t.expires_at AS tenant_expires_at
FROM sessions s
JOIN users u   ON u.id = s.user_id
JOIN tenants t ON t.id = u.tenant_id
WHERE s.token_hash = $1 AND s.expires_at > $2
`

type GetSessionParams struct {
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

type GetSessionRow struct {
	TokenHash       []byte
	CsrfHash        []byte
	ExpiresAt       pgtype.Timestamptz
	LastSeenAt      pgtype.Timestamptz
	UserID          uuid.UUID
	TenantID        uuid.UUID
	Email           string
	Name            string
	Role            UserRole
	TelegramChatID  *int64
	TenantName      string
	Timezone        string
	IsSandbox       bool
	ClockOffset     pgtype.Interval
	Settings        []byte
	Autopilot       bool
	Seed            int64
	TenantExpiresAt pgtype.Timestamptz
}

// Кросс-тенантный: тенант определяется как раз по сессии.
// Отдаёт сразу и пользователя, чтобы не ходить в БД дважды на каждый запрос.
func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, arg.TokenHash, arg.ExpiresAt)
	var i GetSessionRow
	err := row.Scan(
		&i.TokenHash,
		&i.CsrfHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.UserID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.TelegramChatID,
		&i.TenantName,
		&i.Timezone,
		&i.IsSandbox,
		&i.ClockOffset,
		&i.Settings,
		&i.Autopilot,
		&i.Seed,
		&i.TenantExpiresAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, tenant_id, email, password_hash, name, role, telegram_chat_id, created_at FROM users WHERE email = lower($1)
`

// Запросы входа и сессий.
//
// Часть из них выполняется от обслуживающей роли (BYPASSRLS): в момент входа
// и разбора сессии тенант ещё не известен (ADR-005). Такие запросы помечены
// в комментарии.
// Кросс-тенантный: email уникален глобально. Только обслуживающая роль.
func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.TelegramChatID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, password_hash, name, role, telegram_chat_id, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.TelegramChatID,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (id, tenant_id, user_id, action, entity, entity_id, diff, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditLogParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	UserID   uuid.NullUUID
	Action   string
	Entity   string
	EntityID uuid.NullUUID
	Diff     []byte
	Ip       *netip.Addr
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Diff,
		arg.Ip,
	)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, email, password_hash, name, role, telegram_chat_id, created_at FROM users WHERE tenant_id = $1 ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context, tenantID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Role,
			&i.TelegramChatID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserTelegramChatID = `-- name: SetUserTelegramChatID :exec
UPDATE users SET telegram_chat_id = $2 WHERE id = $1
`

type SetUserTelegramChatIDParams struct {
	ID             uuid.UUID
	TelegramChatID *int64
}

func (q *Queries) SetUserTelegramChatID(ctx context.Context, arg SetUserTelegramChatIDParams) error {
	_, err := q.db.Exec(ctx, setUserTelegramChatID, arg.ID, arg.TelegramChatID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = $2, expires_at = $3 WHERE token_hash = $1
`

type TouchSessionParams struct {
	TokenHash  []byte
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

// Продление срока сессии; last_seen_at заодно показывает активность.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.TokenHash, arg.LastSeenAt, arg.ExpiresAt)
	return err
}

const useTelegramLinkCode = `-- name: UseTelegramLinkCode :one
UPDATE telegram_link_codes
SET used_at = $2
WHERE code = $1 AND used_at IS NULL AND expires_at > $2
RETURNING tenant_id, user_id
`

type UseTelegramLinkCodeParams struct {
	Code   string
	UsedAt pgtype.Timestamptz
}

type UseTelegramLinkCodeRow struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

// Код одноразовый: помечаем использованным той же командой, что и читаем.
func (q *Queries) UseTelegramLinkCode(ctx context.Context, arg UseTelegramLinkCodeParams) (UseTelegramLinkCodeRow, error) {
	row := q.db.QueryRow(ctx, useTelegramLinkCode, arg.Code, arg.UsedAt)
	var i UseTelegramLinkCodeRow
	err := row.Scan(&i.TenantID, &i.UserID)
	return i, err
}
