// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const archiveItem = `-- name: ArchiveItem :exec
UPDATE items SET archived_at = $3 WHERE tenant_id = $1 AND id = $2
`

type ArchiveItemParams struct {
	TenantID   uuid.UUID
	ID         uuid.UUID
	ArchivedAt pgtype.Timestamptz
}

// Позиция не удаляется, а архивируется (FR-1): её движения остаются в журнале.
func (q *Queries) ArchiveItem(ctx context.Context, arg ArchiveItemParams) error {
	_, err := q.db.Exec(ctx, archiveItem, arg.TenantID, arg.ID, arg.ArchivedAt)
	return err
}

const archiveSupplier = `-- name: ArchiveSupplier :exec
UPDATE suppliers SET archived_at = $3 WHERE tenant_id = $1 AND id = $2
`

type ArchiveSupplierParams struct {
	TenantID   uuid.UUID
	ID         uuid.UUID
	ArchivedAt pgtype.Timestamptz
}

func (q *Queries) ArchiveSupplier(ctx context.Context, arg ArchiveSupplierParams) error {
	_, err := q.db.Exec(ctx, archiveSupplier, arg.TenantID, arg.ID, arg.ArchivedAt)
	return err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, tenant_id, name)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, created_at
`

type CreateCategoryParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Name     string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.ID, arg.TenantID, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    id, tenant_id, category_id, name, base_unit,
    default_supplier_id, service_level, manual_min_qty
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, category_id, name, base_unit, default_supplier_id, service_level, manual_min_qty, archived_at, created_at
`

type CreateItemParams struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	CategoryID        uuid.NullUUID
	Name              string
	BaseUnit          string
	DefaultSupplierID uuid.NullUUID
	ServiceLevel      int16
	ManualMinQty      decimal.Decimal
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.ID,
		arg.TenantID,
		arg.CategoryID,
		arg.Name,
		arg.BaseUnit,
		arg.DefaultSupplierID,
		arg.ServiceLevel,
		arg.ManualMinQty,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.BaseUnit,
		&i.DefaultSupplierID,
		&i.ServiceLevel,
		&i.ManualMinQty,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (id, tenant_id, name, contact, lead_time_days, delivery_weekdays, order_cutoff)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, name, contact, lead_time_days, delivery_weekdays, order_cutoff, archived_at, created_at
`

type CreateSupplierParams struct {
	ID               uuid.UUID
	TenantID         uuid.UUID
	Name             string
	Contact          string
	LeadTimeDays     int16
	DeliveryWeekdays []int16
	OrderCutoff      pgtype.Time
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Contact,
		arg.LeadTimeDays,
		arg.DeliveryWeekdays,
		arg.OrderCutoff,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Contact,
		&i.LeadTimeDays,
		&i.DeliveryWeekdays,
		&i.OrderCutoff,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWarehouse = `-- name: CreateWarehouse :one
INSERT INTO warehouses (id, tenant_id, name) VALUES ($1, $2, $3) RETURNING id, tenant_id, name, created_at
`

type CreateWarehouseParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Name     string
}

func (q *Queries) CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (Warehouse, error) {
	row := q.db.QueryRow(ctx, createWarehouse, arg.ID, arg.TenantID, arg.Name)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, tenant_id, name, created_at FROM categories WHERE tenant_id = $1 AND lower(name) = lower($2)
`

type GetCategoryByNameParams struct {
	TenantID uuid.UUID
	Lower    string
}

func (q *Queries) GetCategoryByName(ctx context.Context, arg GetCategoryByNameParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, arg.TenantID, arg.Lower)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getDefaultWarehouse = `-- name: GetDefaultWarehouse :one
SELECT id, tenant_id, name, created_at FROM warehouses WHERE tenant_id = $1 ORDER BY created_at LIMIT 1
`

// В MVP у организации один склад (§1, допущения).
func (q *Queries) GetDefaultWarehouse(ctx context.Context, tenantID uuid.UUID) (Warehouse, error) {
	row := q.db.QueryRow(ctx, getDefaultWarehouse, tenantID)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, tenant_id, category_id, name, base_unit, default_supplier_id, service_level, manual_min_qty, archived_at, created_at FROM items WHERE tenant_id = $1 AND id = $2
`

type GetItemParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetItem(ctx context.Context, arg GetItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, arg.TenantID, arg.ID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.BaseUnit,
		&i.DefaultSupplierID,
		&i.ServiceLevel,
		&i.ManualMinQty,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getItemByName = `-- name: GetItemByName :one
SELECT id, tenant_id, category_id, name, base_unit, default_supplier_id, service_level, manual_min_qty, archived_at, created_at FROM items WHERE tenant_id = $1 AND lower(name) = lower($2)
`

type GetItemByNameParams struct {
	TenantID uuid.UUID
	Lower    string
}

func (q *Queries) GetItemByName(ctx context.Context, arg GetItemByNameParams) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByName, arg.TenantID, arg.Lower)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.BaseUnit,
		&i.DefaultSupplierID,
		&i.ServiceLevel,
		&i.ManualMinQty,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSupplier = `-- name: GetSupplier :one
SELECT id, tenant_id, name, contact, lead_time_days, delivery_weekdays, order_cutoff, archived_at, created_at FROM suppliers WHERE tenant_id = $1 AND id = $2
`

type GetSupplierParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetSupplier(ctx context.Context, arg GetSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplier, arg.TenantID, arg.ID)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Contact,
		&i.LeadTimeDays,
		&i.DeliveryWeekdays,
		&i.OrderCutoff,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSupplierByName = `-- name: GetSupplierByName :one
SELECT id, tenant_id, name, contact, lead_time_days, delivery_weekdays, order_cutoff, archived_at, created_at FROM suppliers WHERE tenant_id = $1 AND lower(name) = lower($2)
`

type GetSupplierByNameParams struct {
	TenantID uuid.UUID
	Lower    string
}

func (q *Queries) GetSupplierByName(ctx context.Context, arg GetSupplierByNameParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByName, arg.TenantID, arg.Lower)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Contact,
		&i.LeadTimeDays,
		&i.DeliveryWeekdays,
		&i.OrderCutoff,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSupplierItem = `-- name: GetSupplierItem :one
SELECT tenant_id, supplier_id, item_id, purchase_unit, unit_factor, min_order_qty, pack_multiple, price FROM supplier_items
WHERE tenant_id = $1 AND supplier_id = $2 AND item_id = $3
`

type GetSupplierItemParams struct {
	TenantID   uuid.UUID
	SupplierID uuid.UUID
	ItemID     uuid.UUID
}

func (q *Queries) GetSupplierItem(ctx context.Context, arg GetSupplierItemParams) (SupplierItem, error) {
	row := q.db.QueryRow(ctx, getSupplierItem, arg.TenantID, arg.SupplierID, arg.ItemID)
	var i SupplierItem
	err := row.Scan(
		&i.TenantID,
		&i.SupplierID,
		&i.ItemID,
		&i.PurchaseUnit,
		&i.UnitFactor,
		&i.MinOrderQty,
		&i.PackMultiple,
		&i.Price,
	)
	return i, err
}

const getSupplierItemForItem = `-- name: GetSupplierItemForItem :one
SELECT si.tenant_id, si.supplier_id, si.item_id, si.purchase_unit, si.unit_factor, si.min_order_qty, si.pack_multiple, si.price FROM supplier_items si
JOIN items i ON i.tenant_id = si.tenant_id AND i.id = si.item_id
WHERE si.tenant_id = $1 AND si.item_id = $2 AND si.supplier_id = i.default_supplier_id
`

type GetSupplierItemForItemParams struct {
	TenantID uuid.UUID
	ItemID   uuid.UUID
}

// Условия закупки у поставщика по умолчанию — их и берёт расчёт заказа.
func (q *Queries) GetSupplierItemForItem(ctx context.Context, arg GetSupplierItemForItemParams) (SupplierItem, error) {
	row := q.db.QueryRow(ctx, getSupplierItemForItem, arg.TenantID, arg.ItemID)
	var i SupplierItem
	err := row.Scan(
		&i.TenantID,
		&i.SupplierID,
		&i.ItemID,
		&i.PurchaseUnit,
		&i.UnitFactor,
		&i.MinOrderQty,
		&i.PackMultiple,
		&i.Price,
	)
	return i, err
}

const listActiveItemIDs = `-- name: ListActiveItemIDs :many
SELECT id FROM items WHERE tenant_id = $1 AND archived_at IS NULL ORDER BY id
`

func (q *Queries) ListActiveItemIDs(ctx context.Context, tenantID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveItemIDs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many

SELECT id, tenant_id, name, created_at FROM categories WHERE tenant_id = $1 ORDER BY name
`

// Номенклатура, категории и поставщики (§3.1, §3.2).
//
// Везде есть tenant_id: RLS уже отсечёт чужое, но явный предикат нужен
// планировщику — tenant_id стоит первым в составных индексах.
func (q *Queries) ListCategories(ctx context.Context, tenantID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT
    i.id, i.tenant_id, i.category_id, i.name, i.base_unit, i.default_supplier_id, i.service_level, i.manual_min_qty, i.archived_at, i.created_at,
    c.name AS category_name,
    s.name AS supplier_name
FROM items i
LEFT JOIN categories c ON c.tenant_id = i.tenant_id AND c.id = i.category_id
LEFT JOIN suppliers  s ON s.tenant_id = i.tenant_id AND s.id = i.default_supplier_id
WHERE i.tenant_id = $1
  AND (i.archived_at IS NULL OR $2::boolean)
ORDER BY i.name
`

type ListItemsParams struct {
	TenantID        uuid.UUID
	IncludeArchived bool
}

type ListItemsRow struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	CategoryID        uuid.NullUUID
	Name              string
	BaseUnit          string
	DefaultSupplierID uuid.NullUUID
	ServiceLevel      int16
	ManualMinQty      decimal.Decimal
	ArchivedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	CategoryName      *string
	SupplierName      *string
}

// Таблица позиций дашборда: до 500 строк без пагинации (§6.1).
func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]ListItemsRow, error) {
	rows, err := q.db.Query(ctx, listItems, arg.TenantID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsRow{}
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.Name,
			&i.BaseUnit,
			&i.DefaultSupplierID,
			&i.ServiceLevel,
			&i.ManualMinQty,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.CategoryName,
			&i.SupplierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierItems = `-- name: ListSupplierItems :many
SELECT tenant_id, supplier_id, item_id, purchase_unit, unit_factor, min_order_qty, pack_multiple, price FROM supplier_items WHERE tenant_id = $1 AND supplier_id = $2
`

type ListSupplierItemsParams struct {
	TenantID   uuid.UUID
	SupplierID uuid.UUID
}

func (q *Queries) ListSupplierItems(ctx context.Context, arg ListSupplierItemsParams) ([]SupplierItem, error) {
	rows, err := q.db.Query(ctx, listSupplierItems, arg.TenantID, arg.SupplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupplierItem{}
	for rows.Next() {
		var i SupplierItem
		if err := rows.Scan(
			&i.TenantID,
			&i.SupplierID,
			&i.ItemID,
			&i.PurchaseUnit,
			&i.UnitFactor,
			&i.MinOrderQty,
			&i.PackMultiple,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, tenant_id, name, contact, lead_time_days, delivery_weekdays, order_cutoff, archived_at, created_at FROM suppliers
WHERE tenant_id = $1 AND (archived_at IS NULL OR $2::boolean)
ORDER BY name
`

type ListSuppliersParams struct {
	TenantID        uuid.UUID
	IncludeArchived bool
}

func (q *Queries) ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, listSuppliers, arg.TenantID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Contact,
			&i.LeadTimeDays,
			&i.DeliveryWeekdays,
			&i.OrderCutoff,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarehouses = `-- name: ListWarehouses :many
SELECT id, tenant_id, name, created_at FROM warehouses WHERE tenant_id = $1 ORDER BY name
`

func (q *Queries) ListWarehouses(ctx context.Context, tenantID uuid.UUID) ([]Warehouse, error) {
	rows, err := q.db.Query(ctx, listWarehouses, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Warehouse{}
	for rows.Next() {
		var i Warehouse
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items SET
    name                = COALESCE($3, name),
    category_id         = COALESCE($4, category_id),
    default_supplier_id = COALESCE($5, default_supplier_id),
    service_level       = COALESCE($6, service_level),
    manual_min_qty      = COALESCE($7, manual_min_qty)
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, category_id, name, base_unit, default_supplier_id, service_level, manual_min_qty, archived_at, created_at
`

type UpdateItemParams struct {
	TenantID          uuid.UUID
	ID                uuid.UUID
	Name              *string
	CategoryID        uuid.NullUUID
	DefaultSupplierID uuid.NullUUID
	ServiceLevel      *int16
	ManualMinQty      decimal.NullDecimal
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.CategoryID,
		arg.DefaultSupplierID,
		arg.ServiceLevel,
		arg.ManualMinQty,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.BaseUnit,
		&i.DefaultSupplierID,
		&i.ServiceLevel,
		&i.ManualMinQty,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE suppliers SET
    name              = COALESCE($3, name),
    contact           = COALESCE($4, contact),
    lead_time_days    = COALESCE($5, lead_time_days),
    delivery_weekdays = COALESCE($6, delivery_weekdays),
    order_cutoff      = COALESCE($7, order_cutoff)
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, name, contact, lead_time_days, delivery_weekdays, order_cutoff, archived_at, created_at
`

type UpdateSupplierParams struct {
	TenantID         uuid.UUID
	ID               uuid.UUID
	Name             *string
	Contact          *string
	LeadTimeDays     *int16
	DeliveryWeekdays []int16
	OrderCutoff      pgtype.Time
}

// COALESCE позволяет прислать только изменённые поля (PATCH).
func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, updateSupplier,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.Contact,
		arg.LeadTimeDays,
		arg.DeliveryWeekdays,
		arg.OrderCutoff,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Contact,
		&i.LeadTimeDays,
		&i.DeliveryWeekdays,
		&i.OrderCutoff,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSupplierItem = `-- name: UpsertSupplierItem :one
INSERT INTO supplier_items (
    tenant_id, supplier_id, item_id, purchase_unit,
    unit_factor, min_order_qty, pack_multiple, price
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (supplier_id, item_id) DO UPDATE SET
    purchase_unit = EXCLUDED.purchase_unit,
    unit_factor   = EXCLUDED.unit_factor,
    min_order_qty = EXCLUDED.min_order_qty,
    pack_multiple = EXCLUDED.pack_multiple,
    price         = EXCLUDED.price
RETURNING tenant_id, supplier_id, item_id, purchase_unit, unit_factor, min_order_qty, pack_multiple, price
`

type UpsertSupplierItemParams struct {
	TenantID     uuid.UUID
	SupplierID   uuid.UUID
	ItemID       uuid.UUID
	PurchaseUnit string
	UnitFactor   decimal.Decimal
	MinOrderQty  decimal.Decimal
	PackMultiple decimal.Decimal
	Price        decimal.NullDecimal
}

func (q *Queries) UpsertSupplierItem(ctx context.Context, arg UpsertSupplierItemParams) (SupplierItem, error) {
	row := q.db.QueryRow(ctx, upsertSupplierItem,
		arg.TenantID,
		arg.SupplierID,
		arg.ItemID,
		arg.PurchaseUnit,
		arg.UnitFactor,
		arg.MinOrderQty,
		arg.PackMultiple,
		arg.Price,
	)
	var i SupplierItem
	err := row.Scan(
		&i.TenantID,
		&i.SupplierID,
		&i.ItemID,
		&i.PurchaseUnit,
		&i.UnitFactor,
		&i.MinOrderQty,
		&i.PackMultiple,
		&i.Price,
	)
	return i, err
}
