// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const dashboard = `-- name: Dashboard :many

SELECT
    i.id                                   AS item_id,
    i.name                                 AS item_name,
    i.base_unit,
    i.manual_min_qty,
    c.name                                 AS category_name,
    COALESCE(b.on_hand, 0)::numeric        AS on_hand,
    COALESCE(st.on_order, 0)::numeric      AS on_order,
    COALESCE(st.status, 'no_forecast')     AS status,
    st.stockout_date,
    st.order_by,
    COALESCE(st.recommended_qty, 0)::numeric AS recommended_qty,
    COALESCE(st.target_level, 0)::numeric    AS target_level,
    s.id                                   AS supplier_id,
    s.name                                 AS supplier_name,
    s.order_cutoff,
    COALESCE(si.purchase_unit, '')         AS purchase_unit,
    COALESCE(si.unit_factor, 1)::numeric   AS unit_factor,
    fm.model                               AS forecast_model,
    COALESCE(fm.wape, 1)::double precision AS wape,
    b.updated_at                           AS balance_updated_at
FROM items i
LEFT JOIN categories c      ON c.tenant_id = i.tenant_id AND c.id = i.category_id
LEFT JOIN stock_balances b  ON b.tenant_id = i.tenant_id AND b.item_id = i.id
LEFT JOIN item_status st    ON st.tenant_id = i.tenant_id AND st.item_id = i.id
LEFT JOIN suppliers s       ON s.tenant_id = i.tenant_id AND s.id = i.default_supplier_id
LEFT JOIN supplier_items si ON si.tenant_id = i.tenant_id
                           AND si.item_id = i.id
                           AND si.supplier_id = i.default_supplier_id
LEFT JOIN forecast_metrics fm ON fm.tenant_id = i.tenant_id AND fm.item_id = i.id
WHERE i.tenant_id = $1 AND i.archived_at IS NULL
ORDER BY
    -- Красные сверху, дальше по дате «хватит до» (§6.1).
    CASE COALESCE(st.status, 'no_forecast')
        WHEN 'out_of_stock' THEN 0
        WHEN 'critical'     THEN 1
        WHEN 'order_today'  THEN 2
        WHEN 'no_forecast'  THEN 3
        ELSE 4
    END,
    st.stockout_date NULLS LAST,
    i.name
`

type DashboardRow struct {
	ItemID           uuid.UUID
	ItemName         string
	BaseUnit         string
	ManualMinQty     decimal.Decimal
	CategoryName     *string
	OnHand           decimal.Decimal
	OnOrder          decimal.Decimal
	Status           ItemStatusCode
	StockoutDate     pgtype.Date
	OrderBy          pgtype.Timestamptz
	RecommendedQty   decimal.Decimal
	TargetLevel      decimal.Decimal
	SupplierID       uuid.NullUUID
	SupplierName     *string
	OrderCutoff      pgtype.Time
	PurchaseUnit     string
	UnitFactor       decimal.Decimal
	ForecastModel    *ForecastModel
	Wape             float64
	BalanceUpdatedAt pgtype.Timestamptz
}

// Дашборд собирается одним запросом (§9.2, исключение из правила
// «не ходить в чужие таблицы»): экран должен отвечать за 300 мс на 300 позициях.
func (q *Queries) Dashboard(ctx context.Context, tenantID uuid.UUID) ([]DashboardRow, error) {
	rows, err := q.db.Query(ctx, dashboard, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardRow{}
	for rows.Next() {
		var i DashboardRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemName,
			&i.BaseUnit,
			&i.ManualMinQty,
			&i.CategoryName,
			&i.OnHand,
			&i.OnOrder,
			&i.Status,
			&i.StockoutDate,
			&i.OrderBy,
			&i.RecommendedQty,
			&i.TargetLevel,
			&i.SupplierID,
			&i.SupplierName,
			&i.OrderCutoff,
			&i.PurchaseUnit,
			&i.UnitFactor,
			&i.ForecastModel,
			&i.Wape,
			&i.BalanceUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const itemHistory = `-- name: ItemHistory :many
SELECT day, qty, has_data, stockout
FROM daily_consumption
WHERE tenant_id = $1 AND item_id = $2 AND day >= $3
ORDER BY day
`

type ItemHistoryParams struct {
	TenantID uuid.UUID
	ItemID   uuid.UUID
	Day      pgtype.Date
}

type ItemHistoryRow struct {
	Day      pgtype.Date
	Qty      decimal.Decimal
	HasData  bool
	Stockout bool
}

// График спроса: фактический расход за N дней (§6.2).
func (q *Queries) ItemHistory(ctx context.Context, arg ItemHistoryParams) ([]ItemHistoryRow, error) {
	rows, err := q.db.Query(ctx, itemHistory, arg.TenantID, arg.ItemID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemHistoryRow{}
	for rows.Next() {
		var i ItemHistoryRow
		if err := rows.Scan(
			&i.Day,
			&i.Qty,
			&i.HasData,
			&i.Stockout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const itemInsights = `-- name: ItemInsights :one
SELECT
    i.id           AS item_id,
    i.name         AS item_name,
    i.base_unit,
    i.service_level,
    i.manual_min_qty,
    c.name         AS category_name,
    COALESCE(b.on_hand, 0)::numeric   AS on_hand,
    COALESCE(st.on_order, 0)::numeric AS on_order,
    COALESCE(st.status, 'no_forecast') AS status,
    st.stockout_date,
    st.order_by,
    COALESCE(st.recommended_qty, 0)::numeric AS recommended_qty,
    COALESCE(st.target_level, 0)::numeric    AS target_level,
    COALESCE(st.safety_stock, 0)::numeric    AS safety_stock,
    COALESCE(st.explanation, '{}'::jsonb)    AS explanation,
    s.id           AS supplier_id,
    s.name         AS supplier_name,
    COALESCE(si.purchase_unit, '')       AS purchase_unit,
    COALESCE(si.unit_factor, 1)::numeric AS unit_factor,
    fm.model       AS forecast_model,
    COALESCE(fm.wape, 1)::double precision  AS wape,
    COALESCE(fm.bias, 0)::double precision  AS bias,
    COALESCE(fm.sigma, 0)::double precision AS sigma,
    COALESCE(fm.days_with_data, 0)          AS days_with_data
FROM items i
LEFT JOIN categories c      ON c.tenant_id = i.tenant_id AND c.id = i.category_id
LEFT JOIN stock_balances b  ON b.tenant_id = i.tenant_id AND b.item_id = i.id
LEFT JOIN item_status st    ON st.tenant_id = i.tenant_id AND st.item_id = i.id
LEFT JOIN suppliers s       ON s.tenant_id = i.tenant_id AND s.id = i.default_supplier_id
LEFT JOIN supplier_items si ON si.tenant_id = i.tenant_id
                           AND si.item_id = i.id
                           AND si.supplier_id = i.default_supplier_id
LEFT JOIN forecast_metrics fm ON fm.tenant_id = i.tenant_id AND fm.item_id = i.id
WHERE i.tenant_id = $1 AND i.id = $2
`

type ItemInsightsParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type ItemInsightsRow struct {
	ItemID         uuid.UUID
	ItemName       string
	BaseUnit       string
	ServiceLevel   int16
	ManualMinQty   decimal.Decimal
	CategoryName   *string
	OnHand         decimal.Decimal
	OnOrder        decimal.Decimal
	Status         ItemStatusCode
	StockoutDate   pgtype.Date
	OrderBy        pgtype.Timestamptz
	RecommendedQty decimal.Decimal
	TargetLevel    decimal.Decimal
	SafetyStock    decimal.Decimal
	Explanation    []byte
	SupplierID     uuid.NullUUID
	SupplierName   *string
	PurchaseUnit   string
	UnitFactor     decimal.Decimal
	ForecastModel  *ForecastModel
	Wape           float64
	Bias           float64
	Sigma          float64
	DaysWithData   int16
}

// Карточка позиции: параметры, статус, объяснение и точность (§6.2).
func (q *Queries) ItemInsights(ctx context.Context, arg ItemInsightsParams) (ItemInsightsRow, error) {
	row := q.db.QueryRow(ctx, itemInsights, arg.TenantID, arg.ID)
	var i ItemInsightsRow
	err := row.Scan(
		&i.ItemID,
		&i.ItemName,
		&i.BaseUnit,
		&i.ServiceLevel,
		&i.ManualMinQty,
		&i.CategoryName,
		&i.OnHand,
		&i.OnOrder,
		&i.Status,
		&i.StockoutDate,
		&i.OrderBy,
		&i.RecommendedQty,
		&i.TargetLevel,
		&i.SafetyStock,
		&i.Explanation,
		&i.SupplierID,
		&i.SupplierName,
		&i.PurchaseUnit,
		&i.UnitFactor,
		&i.ForecastModel,
		&i.Wape,
		&i.Bias,
		&i.Sigma,
		&i.DaysWithData,
	)
	return i, err
}

const suggestions = `-- name: Suggestions :many
SELECT
    s.id                                  AS supplier_id,
    s.name                                AS supplier_name,
    s.contact,
    s.order_cutoff,
    i.id                                  AS item_id,
    i.name                                AS item_name,
    i.base_unit,
    COALESCE(b.on_hand, 0)::numeric       AS on_hand,
    st.status,
    st.stockout_date,
    st.order_by,
    st.recommended_qty,
    COALESCE(si.purchase_unit, '')        AS purchase_unit,
    COALESCE(si.unit_factor, 1)::numeric  AS unit_factor,
    si.price
FROM item_status st
JOIN items i     ON i.tenant_id = st.tenant_id AND i.id = st.item_id
JOIN suppliers s ON s.tenant_id = st.tenant_id AND s.id = st.supplier_id
LEFT JOIN stock_balances b  ON b.tenant_id = st.tenant_id AND b.item_id = st.item_id
LEFT JOIN supplier_items si ON si.tenant_id = st.tenant_id
                           AND si.item_id = st.item_id
                           AND si.supplier_id = st.supplier_id
WHERE st.tenant_id = $1
  AND st.status IN ('order_today', 'critical', 'out_of_stock')
  AND st.recommended_qty > 0
  AND i.archived_at IS NULL
ORDER BY s.name, i.name
`

type SuggestionsRow struct {
	SupplierID     uuid.UUID
	SupplierName   string
	Contact        string
	OrderCutoff    pgtype.Time
	ItemID         uuid.UUID
	ItemName       string
	BaseUnit       string
	OnHand         decimal.Decimal
	Status         ItemStatusCode
	StockoutDate   pgtype.Date
	OrderBy        pgtype.Timestamptz
	RecommendedQty decimal.Decimal
	PurchaseUnit   string
	UnitFactor     decimal.Decimal
	Price          decimal.NullDecimal
}

// Блок «Заказать сегодня», сгруппированный по поставщикам (§6).
func (q *Queries) Suggestions(ctx context.Context, tenantID uuid.UUID) ([]SuggestionsRow, error) {
	rows, err := q.db.Query(ctx, suggestions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SuggestionsRow{}
	for rows.Next() {
		var i SuggestionsRow
		if err := rows.Scan(
			&i.SupplierID,
			&i.SupplierName,
			&i.Contact,
			&i.OrderCutoff,
			&i.ItemID,
			&i.ItemName,
			&i.BaseUnit,
			&i.OnHand,
			&i.Status,
			&i.StockoutDate,
			&i.OrderBy,
			&i.RecommendedQty,
			&i.PurchaseUnit,
			&i.UnitFactor,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
