// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forecast.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const bulkUpsertDailyConsumption = `-- name: BulkUpsertDailyConsumption :execrows
INSERT INTO daily_consumption (tenant_id, item_id, day, qty, has_data, stockout)
SELECT
    $1::uuid,
    d.item_id, d.day, d.qty, d.has_data, d.stockout
FROM (
    SELECT
        unnest($2::uuid[])      AS item_id,
        unnest($3::date[])          AS day,
        unnest($4::numeric[]) AS qty,
        unnest($5::boolean[])   AS has_data,
        unnest($6::boolean[])  AS stockout
) AS d
ON CONFLICT (item_id, day) DO UPDATE SET
    qty      = EXCLUDED.qty,
    has_data = EXCLUDED.has_data,
    stockout = EXCLUDED.stockout
`

type BulkUpsertDailyConsumptionParams struct {
	TenantID   uuid.UUID
	ItemIds    []uuid.UUID
	Days       []pgtype.Date
	Quantities []decimal.Decimal
	HasData    []bool
	Stockouts  []bool
}

// Ночной пересчёт переписывает ряд целиком: у 40 позиций за 90 дней это
// 3600 строк, и поштучные запросы не укладываются в бюджет задачи (§12).
func (q *Queries) BulkUpsertDailyConsumption(ctx context.Context, arg BulkUpsertDailyConsumptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkUpsertDailyConsumption,
		arg.TenantID,
		arg.ItemIds,
		arg.Days,
		arg.Quantities,
		arg.HasData,
		arg.Stockouts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkUpsertForecasts = `-- name: BulkUpsertForecasts :execrows
INSERT INTO forecasts (tenant_id, item_id, day, qty, model, computed_at)
SELECT
    $1::uuid,
    f.item_id, f.day, f.qty, f.model,
    $2::timestamptz
FROM (
    SELECT
        unnest($3::uuid[])      AS item_id,
        unnest($4::date[])          AS day,
        unnest($5::numeric[]) AS qty,
        -- Модели идут как text[]: pgx не кодирует срез пользовательского
        -- enum-типа, приведение делает база.
        unnest($6::text[])::forecast_model AS model
) AS f
ON CONFLICT (item_id, day) DO UPDATE SET
    qty         = EXCLUDED.qty,
    model       = EXCLUDED.model,
    computed_at = EXCLUDED.computed_at
`

type BulkUpsertForecastsParams struct {
	TenantID   uuid.UUID
	ComputedAt pgtype.Timestamptz
	ItemIds    []uuid.UUID
	Days       []pgtype.Date
	Quantities []decimal.Decimal
	Models     []string
}

func (q *Queries) BulkUpsertForecasts(ctx context.Context, arg BulkUpsertForecastsParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkUpsertForecasts,
		arg.TenantID,
		arg.ComputedAt,
		arg.ItemIds,
		arg.Days,
		arg.Quantities,
		arg.Models,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteForecastsFrom = `-- name: DeleteForecastsFrom :execrows

DELETE FROM forecasts WHERE tenant_id = $1 AND item_id = $2 AND day >= $3
`

type DeleteForecastsFromParams struct {
	TenantID uuid.UUID
	ItemID   uuid.UUID
	Day      pgtype.Date
}

// Прогноз, метрики и read-модель статусов (§4, §5.3).
// Ночной пересчёт идемпотентен: старый горизонт сносится целиком,
// потом пишется новый (§4.4).
func (q *Queries) DeleteForecastsFrom(ctx context.Context, arg DeleteForecastsFromParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteForecastsFrom, arg.TenantID, arg.ItemID, arg.Day)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteForecastsFromForItems = `-- name: DeleteForecastsFromForItems :execrows
DELETE FROM forecasts
WHERE tenant_id = $1
  AND day >= $2
  AND item_id = ANY($3::uuid[])
`

type DeleteForecastsFromForItemsParams struct {
	TenantID uuid.UUID
	Day      pgtype.Date
	ItemIds  []uuid.UUID
}

// Снос старого горизонта у позиций без модели одним запросом.
func (q *Queries) DeleteForecastsFromForItems(ctx context.Context, arg DeleteForecastsFromForItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteForecastsFromForItems, arg.TenantID, arg.Day, arg.ItemIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getForecastMetrics = `-- name: GetForecastMetrics :one
SELECT tenant_id, item_id, model, wape, bias, sigma, alpha, window_days, days_with_data, computed_at FROM forecast_metrics WHERE tenant_id = $1 AND item_id = $2
`

type GetForecastMetricsParams struct {
	TenantID uuid.UUID
	ItemID   uuid.UUID
}

func (q *Queries) GetForecastMetrics(ctx context.Context, arg GetForecastMetricsParams) (ForecastMetric, error) {
	row := q.db.QueryRow(ctx, getForecastMetrics, arg.TenantID, arg.ItemID)
	var i ForecastMetric
	err := row.Scan(
		&i.TenantID,
		&i.ItemID,
		&i.Model,
		&i.Wape,
		&i.Bias,
		&i.Sigma,
		&i.Alpha,
		&i.WindowDays,
		&i.DaysWithData,
		&i.ComputedAt,
	)
	return i, err
}

const getItemForStatus = `-- name: GetItemForStatus :one
SELECT
    i.id                              AS item_id,
    i.name                            AS item_name,
    i.base_unit,
    i.service_level,
    i.manual_min_qty,
    COALESCE(b.on_hand, 0)::numeric   AS on_hand,
    s.id                              AS supplier_id,
    s.name                            AS supplier_name,
    s.lead_time_days,
    s.delivery_weekdays,
    s.order_cutoff,
    COALESCE(si.min_order_qty, 0)::numeric  AS min_order_qty,
    COALESCE(si.pack_multiple, 0)::numeric  AS pack_multiple,
    COALESCE(si.purchase_unit, '')          AS purchase_unit,
    COALESCE(si.unit_factor, 1)::numeric    AS unit_factor,
    COALESCE(fm.sigma, 0)::double precision AS sigma,
    fm.model                          AS metrics_model,
    COALESCE(fm.wape, 1)::double precision  AS wape,
    COALESCE(fm.bias, 0)::double precision  AS bias
FROM items i
LEFT JOIN stock_balances b ON b.tenant_id = i.tenant_id AND b.item_id = i.id
LEFT JOIN suppliers s      ON s.tenant_id = i.tenant_id AND s.id = i.default_supplier_id
LEFT JOIN supplier_items si ON si.tenant_id = i.tenant_id
                           AND si.item_id = i.id
                           AND si.supplier_id = i.default_supplier_id
LEFT JOIN forecast_metrics fm ON fm.tenant_id = i.tenant_id AND fm.item_id = i.id
WHERE i.tenant_id = $1 AND i.id = $2
`

type GetItemForStatusParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetItemForStatusRow struct {
	ItemID           uuid.UUID
	ItemName         string
	BaseUnit         string
	ServiceLevel     int16
	ManualMinQty     decimal.Decimal
	OnHand           decimal.Decimal
	SupplierID       uuid.NullUUID
	SupplierName     *string
	LeadTimeDays     *int16
	DeliveryWeekdays []int16
	OrderCutoff      pgtype.Time
	MinOrderQty      decimal.Decimal
	PackMultiple     decimal.Decimal
	PurchaseUnit     string
	UnitFactor       decimal.Decimal
	Sigma            float64
	MetricsModel     *ForecastModel
	Wape             float64
	Bias             float64
}

// Всё, что нужно расчёту статуса одной позиции, одной строкой:
// параметры позиции, условия поставщика, остаток и σ из бэктеста.
func (q *Queries) GetItemForStatus(ctx context.Context, arg GetItemForStatusParams) (GetItemForStatusRow, error) {
	row := q.db.QueryRow(ctx, getItemForStatus, arg.TenantID, arg.ID)
	var i GetItemForStatusRow
	err := row.Scan(
		&i.ItemID,
		&i.ItemName,
		&i.BaseUnit,
		&i.ServiceLevel,
		&i.ManualMinQty,
		&i.OnHand,
		&i.SupplierID,
		&i.SupplierName,
		&i.LeadTimeDays,
		&i.DeliveryWeekdays,
		&i.OrderCutoff,
		&i.MinOrderQty,
		&i.PackMultiple,
		&i.PurchaseUnit,
		&i.UnitFactor,
		&i.Sigma,
		&i.MetricsModel,
		&i.Wape,
		&i.Bias,
	)
	return i, err
}

const getItemStatus = `-- name: GetItemStatus :one
SELECT tenant_id, item_id, status, on_order, stockout_date, order_by, recommended_qty, target_level, safety_stock, supplier_id, explanation, computed_at FROM item_status WHERE tenant_id = $1 AND item_id = $2
`

type GetItemStatusParams struct {
	TenantID uuid.UUID
	ItemID   uuid.UUID
}

func (q *Queries) GetItemStatus(ctx context.Context, arg GetItemStatusParams) (ItemStatus, error) {
	row := q.db.QueryRow(ctx, getItemStatus, arg.TenantID, arg.ItemID)
	var i ItemStatus
	err := row.Scan(
		&i.TenantID,
		&i.ItemID,
		&i.Status,
		&i.OnOrder,
		&i.StockoutDate,
		&i.OrderBy,
		&i.RecommendedQty,
		&i.TargetLevel,
		&i.SafetyStock,
		&i.SupplierID,
		&i.Explanation,
		&i.ComputedAt,
	)
	return i, err
}

const listConsumptionMovementsForSeries = `-- name: ListConsumptionMovementsForSeries :many
SELECT
    m.item_id,
    (m.occurred_at AT TIME ZONE $2::text)::date AS day,
    m.qty,
    m.count_id
FROM stock_movements m
WHERE m.tenant_id = $1
  AND m.occurred_at >= $3
  AND m.occurred_at < $4
  AND m.type IN ('usage', 'writeoff', 'adjustment')
  AND m.reverses_id IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM stock_movements r
      WHERE r.tenant_id = m.tenant_id AND r.reverses_id = m.id
  )
ORDER BY m.item_id, m.occurred_at
`

type ListConsumptionMovementsForSeriesParams struct {
	TenantID uuid.UUID
	Tz       string
	Since    pgtype.Timestamptz
	Until    pgtype.Timestamptz
}

type ListConsumptionMovementsForSeriesRow struct {
	ItemID  uuid.UUID
	Day     pgtype.Date
	Qty     decimal.Decimal
	CountID uuid.NullUUID
}

// Сырые движения расхода для сборки ряда (§4.1).
//
// Отдаются по одному, а не агрегатом по дням, потому что корректировки
// из пересчёта нужно размазать по интервалу между пересчётами: в режиме
// «только пересчёт» весь расход за несколько дней записан одним движением.
// Сторнированные движения и сами сторно в ряд не попадают.
func (q *Queries) ListConsumptionMovementsForSeries(ctx context.Context, arg ListConsumptionMovementsForSeriesParams) ([]ListConsumptionMovementsForSeriesRow, error) {
	rows, err := q.db.Query(ctx, listConsumptionMovementsForSeries,
		arg.TenantID,
		arg.Tz,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConsumptionMovementsForSeriesRow{}
	for rows.Next() {
		var i ListConsumptionMovementsForSeriesRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Day,
			&i.Qty,
			&i.CountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDaysWithUsage = `-- name: ListDaysWithUsage :many
SELECT DISTINCT d.day FROM (
    SELECT (m.occurred_at AT TIME ZONE $2::text)::date AS day
    FROM stock_movements m
    WHERE m.tenant_id = $1
      AND m.occurred_at >= $3
      AND m.type IN ('usage', 'writeoff', 'adjustment')
    UNION
    SELECT (c.posted_at AT TIME ZONE $2::text)::date AS day
    FROM stock_counts c
    WHERE c.tenant_id = $1 AND c.status = 'posted' AND c.posted_at >= $3
) d
ORDER BY d.day
`

type ListDaysWithUsageParams struct {
	TenantID uuid.UUID
	Tz       string
	Since    pgtype.Timestamptz
}

// День «с данными»: был хотя бы один расход или проведённый пересчёт (§4.1).
func (q *Queries) ListDaysWithUsage(ctx context.Context, arg ListDaysWithUsageParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listDaysWithUsage, arg.TenantID, arg.Tz, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var day pgtype.Date
		if err := rows.Scan(&day); err != nil {
			return nil, err
		}
		items = append(items, day)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForecastForItem = `-- name: ListForecastForItem :many
SELECT day, qty, model FROM forecasts
WHERE tenant_id = $1 AND item_id = $2 AND day >= $3
ORDER BY day
`

type ListForecastForItemParams struct {
	TenantID uuid.UUID
	ItemID   uuid.UUID
	Day      pgtype.Date
}

type ListForecastForItemRow struct {
	Day   pgtype.Date
	Qty   decimal.Decimal
	Model ForecastModel
}

func (q *Queries) ListForecastForItem(ctx context.Context, arg ListForecastForItemParams) ([]ListForecastForItemRow, error) {
	rows, err := q.db.Query(ctx, listForecastForItem, arg.TenantID, arg.ItemID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListForecastForItemRow{}
	for rows.Next() {
		var i ListForecastForItemRow
		if err := rows.Scan(&i.Day, &i.Qty, &i.Model); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForecastMetrics = `-- name: ListForecastMetrics :many
SELECT tenant_id, item_id, model, wape, bias, sigma, alpha, window_days, days_with_data, computed_at FROM forecast_metrics WHERE tenant_id = $1
`

func (q *Queries) ListForecastMetrics(ctx context.Context, tenantID uuid.UUID) ([]ForecastMetric, error) {
	rows, err := q.db.Query(ctx, listForecastMetrics, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ForecastMetric{}
	for rows.Next() {
		var i ForecastMetric
		if err := rows.Scan(
			&i.TenantID,
			&i.ItemID,
			&i.Model,
			&i.Wape,
			&i.Bias,
			&i.Sigma,
			&i.Alpha,
			&i.WindowDays,
			&i.DaysWithData,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForecastsFrom = `-- name: ListForecastsFrom :many
SELECT item_id, day, qty, model FROM forecasts
WHERE tenant_id = $1 AND day >= $2
ORDER BY item_id, day
`

type ListForecastsFromParams struct {
	TenantID uuid.UUID
	Day      pgtype.Date
}

type ListForecastsFromRow struct {
	ItemID uuid.UUID
	Day    pgtype.Date
	Qty    decimal.Decimal
	Model  ForecastModel
}

// Пакетная версия для ночного пересчёта статусов: один запрос на тенанта
// вместо запроса на позицию.
func (q *Queries) ListForecastsFrom(ctx context.Context, arg ListForecastsFromParams) ([]ListForecastsFromRow, error) {
	rows, err := q.db.Query(ctx, listForecastsFrom, arg.TenantID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListForecastsFromRow{}
	for rows.Next() {
		var i ListForecastsFromRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Day,
			&i.Qty,
			&i.Model,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemStatuses = `-- name: ListItemStatuses :many
SELECT tenant_id, item_id, status, on_order, stockout_date, order_by, recommended_qty, target_level, safety_stock, supplier_id, explanation, computed_at FROM item_status WHERE tenant_id = $1
`

func (q *Queries) ListItemStatuses(ctx context.Context, tenantID uuid.UUID) ([]ItemStatus, error) {
	rows, err := q.db.Query(ctx, listItemStatuses, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemStatus{}
	for rows.Next() {
		var i ItemStatus
		if err := rows.Scan(
			&i.TenantID,
			&i.ItemID,
			&i.Status,
			&i.OnOrder,
			&i.StockoutDate,
			&i.OrderBy,
			&i.RecommendedQty,
			&i.TargetLevel,
			&i.SafetyStock,
			&i.SupplierID,
			&i.Explanation,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsForStatus = `-- name: ListItemsForStatus :many
SELECT
    i.id                              AS item_id,
    i.name                            AS item_name,
    i.base_unit,
    i.service_level,
    i.manual_min_qty,
    COALESCE(b.on_hand, 0)::numeric   AS on_hand,
    s.id                              AS supplier_id,
    s.name                            AS supplier_name,
    s.lead_time_days,
    s.delivery_weekdays,
    s.order_cutoff,
    COALESCE(si.min_order_qty, 0)::numeric  AS min_order_qty,
    COALESCE(si.pack_multiple, 0)::numeric  AS pack_multiple,
    COALESCE(si.purchase_unit, '')          AS purchase_unit,
    COALESCE(si.unit_factor, 1)::numeric    AS unit_factor,
    COALESCE(fm.sigma, 0)::double precision AS sigma,
    fm.model                          AS metrics_model,
    COALESCE(fm.wape, 1)::double precision  AS wape,
    COALESCE(fm.bias, 0)::double precision  AS bias
FROM items i
LEFT JOIN stock_balances b ON b.tenant_id = i.tenant_id AND b.item_id = i.id
LEFT JOIN suppliers s      ON s.tenant_id = i.tenant_id AND s.id = i.default_supplier_id
LEFT JOIN supplier_items si ON si.tenant_id = i.tenant_id
                           AND si.item_id = i.id
                           AND si.supplier_id = i.default_supplier_id
LEFT JOIN forecast_metrics fm ON fm.tenant_id = i.tenant_id AND fm.item_id = i.id
WHERE i.tenant_id = $1 AND i.archived_at IS NULL
ORDER BY i.id
`

type ListItemsForStatusRow struct {
	ItemID           uuid.UUID
	ItemName         string
	BaseUnit         string
	ServiceLevel     int16
	ManualMinQty     decimal.Decimal
	OnHand           decimal.Decimal
	SupplierID       uuid.NullUUID
	SupplierName     *string
	LeadTimeDays     *int16
	DeliveryWeekdays []int16
	OrderCutoff      pgtype.Time
	MinOrderQty      decimal.Decimal
	PackMultiple     decimal.Decimal
	PurchaseUnit     string
	UnitFactor       decimal.Decimal
	Sigma            float64
	MetricsModel     *ForecastModel
	Wape             float64
	Bias             float64
}

// Пакетная версия для ночного пересчёта.
func (q *Queries) ListItemsForStatus(ctx context.Context, tenantID uuid.UUID) ([]ListItemsForStatusRow, error) {
	rows, err := q.db.Query(ctx, listItemsForStatus, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsForStatusRow{}
	for rows.Next() {
		var i ListItemsForStatusRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemName,
			&i.BaseUnit,
			&i.ServiceLevel,
			&i.ManualMinQty,
			&i.OnHand,
			&i.SupplierID,
			&i.SupplierName,
			&i.LeadTimeDays,
			&i.DeliveryWeekdays,
			&i.OrderCutoff,
			&i.MinOrderQty,
			&i.PackMultiple,
			&i.PurchaseUnit,
			&i.UnitFactor,
			&i.Sigma,
			&i.MetricsModel,
			&i.Wape,
			&i.Bias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockoutDays = `-- name: ListStockoutDays :many
WITH running AS (
    SELECT
        item_id,
        (occurred_at AT TIME ZONE $2::text)::date AS day,
        sum(qty) OVER (
            PARTITION BY item_id
            ORDER BY occurred_at, id
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS balance
    FROM stock_movements
    WHERE tenant_id = $1 AND occurred_at < $3
)
SELECT item_id, day
FROM running
WHERE balance <= 0
GROUP BY item_id, day
`

type ListStockoutDaysParams struct {
	TenantID uuid.UUID
	Tz       string
	Until    pgtype.Timestamptz
}

type ListStockoutDaysRow struct {
	ItemID uuid.UUID
	Day    pgtype.Date
}

// Дни, когда остаток доходил до нуля: модель не должна учиться на заниженных
// цифрах (§4.1). Остаток восстанавливается из журнала нарастающим итогом.
func (q *Queries) ListStockoutDays(ctx context.Context, arg ListStockoutDaysParams) ([]ListStockoutDaysRow, error) {
	rows, err := q.db.Query(ctx, listStockoutDays, arg.TenantID, arg.Tz, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockoutDaysRow{}
	for rows.Next() {
		var i ListStockoutDaysRow
		if err := rows.Scan(&i.ItemID, &i.Day); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumConsumptionByItemForDay = `-- name: SumConsumptionByItemForDay :many
SELECT item_id, COALESCE(-sum(qty), 0)::numeric AS consumed
FROM stock_movements
WHERE tenant_id = $1
  AND type IN ('usage', 'writeoff', 'adjustment')
  AND (occurred_at AT TIME ZONE $2::text)::date = $3::date
GROUP BY item_id
`

type SumConsumptionByItemForDayParams struct {
	TenantID uuid.UUID
	Tz       string
	Day      pgtype.Date
}

type SumConsumptionByItemForDayRow struct {
	ItemID   uuid.UUID
	Consumed decimal.Decimal
}

func (q *Queries) SumConsumptionByItemForDay(ctx context.Context, arg SumConsumptionByItemForDayParams) ([]SumConsumptionByItemForDayRow, error) {
	rows, err := q.db.Query(ctx, sumConsumptionByItemForDay, arg.TenantID, arg.Tz, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumConsumptionByItemForDayRow{}
	for rows.Next() {
		var i SumConsumptionByItemForDayRow
		if err := rows.Scan(&i.ItemID, &i.Consumed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumConsumptionForDay = `-- name: SumConsumptionForDay :one
SELECT COALESCE(-sum(qty), 0)::numeric AS consumed
FROM stock_movements
WHERE tenant_id = $1
  AND item_id = $2
  AND type IN ('usage', 'writeoff', 'adjustment')
  AND (occurred_at AT TIME ZONE $3::text)::date = $4::date
`

type SumConsumptionForDayParams struct {
	TenantID uuid.UUID
	ItemID   uuid.UUID
	Tz       string
	Day      pgtype.Date
}

// Сколько уже израсходовано сегодня: за сегодняшний день в целевой уровень
// идёт только неизрасходованная часть прогноза (§5.2).
func (q *Queries) SumConsumptionForDay(ctx context.Context, arg SumConsumptionForDayParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, sumConsumptionForDay,
		arg.TenantID,
		arg.ItemID,
		arg.Tz,
		arg.Day,
	)
	var consumed decimal.Decimal
	err := row.Scan(&consumed)
	return consumed, err
}

const upsertForecast = `-- name: UpsertForecast :exec
INSERT INTO forecasts (tenant_id, item_id, day, qty, model, computed_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (item_id, day) DO UPDATE SET
    qty         = EXCLUDED.qty,
    model       = EXCLUDED.model,
    computed_at = EXCLUDED.computed_at
`

type UpsertForecastParams struct {
	TenantID   uuid.UUID
	ItemID     uuid.UUID
	Day        pgtype.Date
	Qty        decimal.Decimal
	Model      ForecastModel
	ComputedAt pgtype.Timestamptz
}

func (q *Queries) UpsertForecast(ctx context.Context, arg UpsertForecastParams) error {
	_, err := q.db.Exec(ctx, upsertForecast,
		arg.TenantID,
		arg.ItemID,
		arg.Day,
		arg.Qty,
		arg.Model,
		arg.ComputedAt,
	)
	return err
}

const upsertForecastMetrics = `-- name: UpsertForecastMetrics :exec
INSERT INTO forecast_metrics (
    tenant_id, item_id, model, wape, bias, sigma, alpha,
    window_days, days_with_data, computed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (item_id) DO UPDATE SET
    model          = EXCLUDED.model,
    wape           = EXCLUDED.wape,
    bias           = EXCLUDED.bias,
    sigma          = EXCLUDED.sigma,
    alpha          = EXCLUDED.alpha,
    window_days    = EXCLUDED.window_days,
    days_with_data = EXCLUDED.days_with_data,
    computed_at    = EXCLUDED.computed_at
`

type UpsertForecastMetricsParams struct {
	TenantID     uuid.UUID
	ItemID       uuid.UUID
	Model        ForecastModel
	Wape         float64
	Bias         float64
	Sigma        float64
	Alpha        *float64
	WindowDays   int16
	DaysWithData int16
	ComputedAt   pgtype.Timestamptz
}

func (q *Queries) UpsertForecastMetrics(ctx context.Context, arg UpsertForecastMetricsParams) error {
	_, err := q.db.Exec(ctx, upsertForecastMetrics,
		arg.TenantID,
		arg.ItemID,
		arg.Model,
		arg.Wape,
		arg.Bias,
		arg.Sigma,
		arg.Alpha,
		arg.WindowDays,
		arg.DaysWithData,
		arg.ComputedAt,
	)
	return err
}

const upsertItemStatus = `-- name: UpsertItemStatus :exec
INSERT INTO item_status (
    tenant_id, item_id, status, on_order, stockout_date, order_by,
    recommended_qty, target_level, safety_stock, supplier_id,
    explanation, computed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (item_id) DO UPDATE SET
    status          = EXCLUDED.status,
    on_order        = EXCLUDED.on_order,
    stockout_date   = EXCLUDED.stockout_date,
    order_by        = EXCLUDED.order_by,
    recommended_qty = EXCLUDED.recommended_qty,
    target_level    = EXCLUDED.target_level,
    safety_stock    = EXCLUDED.safety_stock,
    supplier_id     = EXCLUDED.supplier_id,
    explanation     = EXCLUDED.explanation,
    computed_at     = EXCLUDED.computed_at
`

type UpsertItemStatusParams struct {
	TenantID       uuid.UUID
	ItemID         uuid.UUID
	Status         ItemStatusCode
	OnOrder        decimal.Decimal
	StockoutDate   pgtype.Date
	OrderBy        pgtype.Timestamptz
	RecommendedQty decimal.Decimal
	TargetLevel    decimal.Decimal
	SafetyStock    decimal.Decimal
	SupplierID     uuid.NullUUID
	Explanation    []byte
	ComputedAt     pgtype.Timestamptz
}

func (q *Queries) UpsertItemStatus(ctx context.Context, arg UpsertItemStatusParams) error {
	_, err := q.db.Exec(ctx, upsertItemStatus,
		arg.TenantID,
		arg.ItemID,
		arg.Status,
		arg.OnOrder,
		arg.StockoutDate,
		arg.OrderBy,
		arg.RecommendedQty,
		arg.TargetLevel,
		arg.SafetyStock,
		arg.SupplierID,
		arg.Explanation,
		arg.ComputedAt,
	)
	return err
}
