// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type CountStatus string

const (
	CountStatusDraft  CountStatus = "draft"
	CountStatusPosted CountStatus = "posted"
)

func (e *CountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CountStatus(s)
	case string:
		*e = CountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CountStatus: %T", src)
	}
	return nil
}

type NullCountStatus struct {
	CountStatus CountStatus
	Valid       bool // Valid is true if CountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CountStatus), nil
}

type ForecastModel string

const (
	ForecastModelM0 ForecastModel = "M0"
	ForecastModelM1 ForecastModel = "M1"
	ForecastModelM2 ForecastModel = "M2"
)

func (e *ForecastModel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ForecastModel(s)
	case string:
		*e = ForecastModel(s)
	default:
		return fmt.Errorf("unsupported scan type for ForecastModel: %T", src)
	}
	return nil
}

type NullForecastModel struct {
	ForecastModel ForecastModel
	Valid         bool // Valid is true if ForecastModel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullForecastModel) Scan(value interface{}) error {
	if value == nil {
		ns.ForecastModel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ForecastModel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullForecastModel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ForecastModel), nil
}

type ItemStatusCode string

const (
	ItemStatusCodeOutOfStock ItemStatusCode = "out_of_stock"
	ItemStatusCodeCritical   ItemStatusCode = "critical"
	ItemStatusCodeOrderToday ItemStatusCode = "order_today"
	ItemStatusCodeOk         ItemStatusCode = "ok"
	ItemStatusCodeNoForecast ItemStatusCode = "no_forecast"
)

func (e *ItemStatusCode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemStatusCode(s)
	case string:
		*e = ItemStatusCode(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemStatusCode: %T", src)
	}
	return nil
}

type NullItemStatusCode struct {
	ItemStatusCode ItemStatusCode
	Valid          bool // Valid is true if ItemStatusCode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemStatusCode) Scan(value interface{}) error {
	if value == nil {
		ns.ItemStatusCode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemStatusCode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemStatusCode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemStatusCode), nil
}

type MovementType string

const (
	MovementTypeOpening    MovementType = "opening"
	MovementTypeReceipt    MovementType = "receipt"
	MovementTypeUsage      MovementType = "usage"
	MovementTypeWriteoff   MovementType = "writeoff"
	MovementTypeAdjustment MovementType = "adjustment"
	MovementTypeReversal   MovementType = "reversal"
)

func (e *MovementType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MovementType(s)
	case string:
		*e = MovementType(s)
	default:
		return fmt.Errorf("unsupported scan type for MovementType: %T", src)
	}
	return nil
}

type NullMovementType struct {
	MovementType MovementType
	Valid        bool // Valid is true if MovementType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMovementType) Scan(value interface{}) error {
	if value == nil {
		ns.MovementType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MovementType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMovementType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MovementType), nil
}

type NotificationType string

const (
	NotificationTypeDailyDigest     NotificationType = "daily_digest"
	NotificationTypeCritical        NotificationType = "critical"
	NotificationTypeCutoffReminder  NotificationType = "cutoff_reminder"
	NotificationTypeOrderLate       NotificationType = "order_late"
	NotificationTypeReceiptMismatch NotificationType = "receipt_mismatch"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType
	Valid            bool // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type OutboxChannel string

const (
	OutboxChannelTelegram OutboxChannel = "telegram"
	OutboxChannelEmail    OutboxChannel = "email"
)

func (e *OutboxChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxChannel(s)
	case string:
		*e = OutboxChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxChannel: %T", src)
	}
	return nil
}

type NullOutboxChannel struct {
	OutboxChannel OutboxChannel
	Valid         bool // Valid is true if OutboxChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxChannel) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxChannel), nil
}

type OutboxStatus string

const (
	OutboxStatusPending OutboxStatus = "pending"
	OutboxStatusSent    OutboxStatus = "sent"
	OutboxStatusFailed  OutboxStatus = "failed"
)

func (e *OutboxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatus(s)
	case string:
		*e = OutboxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatus: %T", src)
	}
	return nil
}

type NullOutboxStatus struct {
	OutboxStatus OutboxStatus
	Valid        bool // Valid is true if OutboxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatus), nil
}

type PurchaseOrderStatus string

const (
	PurchaseOrderStatusDraft     PurchaseOrderStatus = "draft"
	PurchaseOrderStatusSent      PurchaseOrderStatus = "sent"
	PurchaseOrderStatusReceived  PurchaseOrderStatus = "received"
	PurchaseOrderStatusCancelled PurchaseOrderStatus = "cancelled"
)

func (e *PurchaseOrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PurchaseOrderStatus(s)
	case string:
		*e = PurchaseOrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PurchaseOrderStatus: %T", src)
	}
	return nil
}

type NullPurchaseOrderStatus struct {
	PurchaseOrderStatus PurchaseOrderStatus
	Valid               bool // Valid is true if PurchaseOrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPurchaseOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PurchaseOrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PurchaseOrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPurchaseOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PurchaseOrderStatus), nil
}

type UserRole string

const (
	UserRoleOwner UserRole = "owner"
	UserRoleStaff UserRole = "staff"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AuditLog struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	UserID   uuid.NullUUID
	Action   string
	Entity   string
	EntityID uuid.NullUUID
	Diff     []byte
	Ip       *netip.Addr
	At       pgtype.Timestamptz
}

type Category struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type DailyConsumption struct {
	TenantID uuid.UUID
	ItemID   uuid.UUID
	Day      pgtype.Date
	Qty      decimal.Decimal
	HasData  bool
	Stockout bool
}

type Forecast struct {
	TenantID   uuid.UUID
	ItemID     uuid.UUID
	Day        pgtype.Date
	Qty        decimal.Decimal
	Model      ForecastModel
	ComputedAt pgtype.Timestamptz
}

type ForecastMetric struct {
	TenantID     uuid.UUID
	ItemID       uuid.UUID
	Model        ForecastModel
	Wape         float64
	Bias         float64
	Sigma        float64
	Alpha        *float64
	WindowDays   int16
	DaysWithData int16
	ComputedAt   pgtype.Timestamptz
}

type Item struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	CategoryID        uuid.NullUUID
	Name              string
	BaseUnit          string
	DefaultSupplierID uuid.NullUUID
	ServiceLevel      int16
	ManualMinQty      decimal.Decimal
	ArchivedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type ItemStatus struct {
	TenantID       uuid.UUID
	ItemID         uuid.UUID
	Status         ItemStatusCode
	OnOrder        decimal.Decimal
	StockoutDate   pgtype.Date
	OrderBy        pgtype.Timestamptz
	RecommendedQty decimal.Decimal
	TargetLevel    decimal.Decimal
	SafetyStock    decimal.Decimal
	SupplierID     uuid.NullUUID
	Explanation    []byte
	ComputedAt     pgtype.Timestamptz
}

type Notification struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.NullUUID
	Type      NotificationType
	Payload   []byte
	DedupKey  string
	ReadAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Outbox struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	NotificationID uuid.NullUUID
	Channel        OutboxChannel
	Recipient      string
	Payload        []byte
	Status         OutboxStatus
	Attempts       int16
	NextAttemptAt  pgtype.Timestamptz
	LastError      string
	CreatedAt      pgtype.Timestamptz
	SentAt         pgtype.Timestamptz
}

type PurchaseOrder struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	SupplierID     uuid.UUID
	Status         PurchaseOrderStatus
	ExpectedAt     pgtype.Date
	SentAt         pgtype.Timestamptz
	ReceivedAt     pgtype.Timestamptz
	CancelledAt    pgtype.Timestamptz
	LateNotifiedAt pgtype.Timestamptz
	Note           string
	CreatedBy      uuid.NullUUID
	CreatedAt      pgtype.Timestamptz
}

type PurchaseOrderLine struct {
	TenantID     uuid.UUID
	OrderID      uuid.UUID
	ItemID       uuid.UUID
	QtyOrdered   decimal.Decimal
	QtyReceived  decimal.NullDecimal
	PurchaseUnit string
	UnitFactor   decimal.Decimal
	Price        decimal.NullDecimal
}

type Session struct {
	TokenHash  []byte
	UserID     uuid.UUID
	TenantID   uuid.UUID
	CsrfHash   []byte
	UserAgent  string
	ExpiresAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type StockBalance struct {
	TenantID    uuid.UUID
	WarehouseID uuid.UUID
	ItemID      uuid.UUID
	OnHand      decimal.Decimal
	UpdatedAt   pgtype.Timestamptz
}

type StockCount struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	WarehouseID uuid.UUID
	Status      CountStatus
	Scope       string
	Note        string
	CreatedBy   uuid.NullUUID
	PostedBy    uuid.NullUUID
	PostedAt    pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type StockCountLine struct {
	TenantID    uuid.UUID
	CountID     uuid.UUID
	ItemID      uuid.UUID
	ExpectedQty decimal.Decimal
	CountedQty  decimal.NullDecimal
}

type StockMovement struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	WarehouseID    uuid.UUID
	ItemID         uuid.UUID
	Type           MovementType
	Qty            decimal.Decimal
	OccurredAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	CreatedBy      uuid.NullUUID
	Reason         *string
	Comment        string
	OrderID        uuid.NullUUID
	CountID        uuid.NullUUID
	ReversesID     uuid.NullUUID
	IdempotencyKey *string
}

type Supplier struct {
	ID               uuid.UUID
	TenantID         uuid.UUID
	Name             string
	Contact          string
	LeadTimeDays     int16
	DeliveryWeekdays []int16
	OrderCutoff      pgtype.Time
	ArchivedAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type SupplierItem struct {
	TenantID     uuid.UUID
	SupplierID   uuid.UUID
	ItemID       uuid.UUID
	PurchaseUnit string
	UnitFactor   decimal.Decimal
	MinOrderQty  decimal.Decimal
	PackMultiple decimal.Decimal
	Price        decimal.NullDecimal
}

type TelegramLinkCode struct {
	Code      string
	TenantID  uuid.UUID
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Tenant struct {
	ID          uuid.UUID
	Name        string
	Timezone    string
	IsSandbox   bool
	ExpiresAt   pgtype.Timestamptz
	ClockOffset pgtype.Interval
	Seed        int64
	Autopilot   bool
	Settings    []byte
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	Email          string
	PasswordHash   string
	Name           string
	Role           UserRole
	TelegramChatID *int64
	CreatedAt      pgtype.Timestamptz
}

type Warehouse struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}
