// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notify.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutbox = `-- name: ClaimOutbox :many
UPDATE outbox o SET attempts = o.attempts + 1
WHERE o.id IN (
    SELECT c.id FROM outbox c
    WHERE c.status = 'pending' AND c.next_attempt_at <= $1
    ORDER BY c.next_attempt_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING o.id, o.tenant_id, o.notification_id, o.channel, o.recipient, o.payload, o.status, o.attempts, o.next_attempt_at, o.last_error, o.created_at, o.sent_at
`

type ClaimOutboxParams struct {
	NextAttemptAt pgtype.Timestamptz
	Limit         int32
}

// Воркер забирает пачку. SKIP LOCKED позволяет нескольким воркерам работать
// параллельно, не дожидаясь друг друга (ADR-004).
func (q *Queries) ClaimOutbox(ctx context.Context, arg ClaimOutboxParams) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, claimOutbox, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.NotificationID,
			&i.Channel,
			&i.Recipient,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPendingOutbox = `-- name: CountPendingOutbox :one
SELECT count(*)::int AS pending FROM outbox WHERE status = 'pending'
`

func (q *Queries) CountPendingOutbox(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countPendingOutbox)
	var pending int32
	err := row.Scan(&pending)
	return pending, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)::int AS unread
FROM notifications
WHERE tenant_id = $1 AND read_at IS NULL
  AND (user_id IS NULL OR user_id = $2)
`

type CountUnreadNotificationsParams struct {
	TenantID uuid.UUID
	UserID   uuid.NullUUID
}

func (q *Queries) CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, arg.TenantID, arg.UserID)
	var unread int32
	err := row.Scan(&unread)
	return unread, err
}

const insertNotification = `-- name: InsertNotification :one

INSERT INTO notifications (id, tenant_id, user_id, type, payload, dedup_key, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id, dedup_key) DO NOTHING
RETURNING id, tenant_id, user_id, type, payload, dedup_key, read_at, created_at
`

type InsertNotificationParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.NullUUID
	Type      NotificationType
	Payload   []byte
	DedupKey  string
	CreatedAt pgtype.Timestamptz
}

// Лента, transactional outbox и журнал аудита (§5.5, ADR-004).
// Дедупликация уникальным индексом по (tenant_id, dedup_key):
// повтор молча не создаёт вторую запись.
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Type,
		arg.Payload,
		arg.DedupKey,
		arg.CreatedAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Type,
		&i.Payload,
		&i.DedupKey,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (id, tenant_id, notification_id, channel, recipient, payload, next_attempt_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertOutboxParams struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	NotificationID uuid.NullUUID
	Channel        OutboxChannel
	Recipient      string
	Payload        []byte
	NextAttemptAt  pgtype.Timestamptz
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox,
		arg.ID,
		arg.TenantID,
		arg.NotificationID,
		arg.Channel,
		arg.Recipient,
		arg.Payload,
		arg.NextAttemptAt,
	)
	return err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, tenant_id, user_id, type, payload, dedup_key, read_at, created_at FROM notifications
WHERE tenant_id = $1
  AND ($2::uuid IS NULL OR user_id = $2 OR user_id IS NULL)
  AND (
      $3::timestamptz IS NULL
      OR (created_at, id) < ($3, $4::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListNotificationsParams struct {
	TenantID uuid.UUID
	UserID   uuid.NullUUID
	CursorAt pgtype.Timestamptz
	CursorID uuid.NullUUID
	RowLimit int32
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.TenantID,
		arg.UserID,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Type,
			&i.Payload,
			&i.DedupKey,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipients = `-- name: ListRecipients :many
SELECT id, email, name, role, telegram_chat_id
FROM users
WHERE tenant_id = $1 AND role = 'owner'
`

type ListRecipientsRow struct {
	ID             uuid.UUID
	Email          string
	Name           string
	Role           UserRole
	TelegramChatID *int64
}

// Кому слать: владельцу — сводки и алерты, сотруднику — только лента.
func (q *Queries) ListRecipients(ctx context.Context, tenantID uuid.UUID) ([]ListRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listRecipients, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecipientsRow{}
	for rows.Next() {
		var i ListRecipientsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.TelegramChatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsRead = `-- name: MarkNotificationsRead :execrows
UPDATE notifications SET read_at = $3
WHERE tenant_id = $1 AND read_at IS NULL
  AND (user_id IS NULL OR user_id = $2)
  AND (cardinality($4::uuid[]) = 0 OR id = ANY($4::uuid[]))
`

type MarkNotificationsReadParams struct {
	TenantID uuid.UUID
	UserID   uuid.NullUUID
	ReadAt   pgtype.Timestamptz
	Ids      []uuid.UUID
}

func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationsRead,
		arg.TenantID,
		arg.UserID,
		arg.ReadAt,
		arg.Ids,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE outbox SET status = 'failed', last_error = $2 WHERE id = $1
`

type MarkOutboxFailedParams struct {
	ID        uuid.UUID
	LastError string
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, arg.ID, arg.LastError)
	return err
}

const markOutboxSent = `-- name: MarkOutboxSent :exec
UPDATE outbox SET status = 'sent', sent_at = $2, last_error = '' WHERE id = $1
`

type MarkOutboxSentParams struct {
	ID     uuid.UUID
	SentAt pgtype.Timestamptz
}

func (q *Queries) MarkOutboxSent(ctx context.Context, arg MarkOutboxSentParams) error {
	_, err := q.db.Exec(ctx, markOutboxSent, arg.ID, arg.SentAt)
	return err
}

const rescheduleOutbox = `-- name: RescheduleOutbox :exec
UPDATE outbox SET next_attempt_at = $2, last_error = $3 WHERE id = $1
`

type RescheduleOutboxParams struct {
	ID            uuid.UUID
	NextAttemptAt pgtype.Timestamptz
	LastError     string
}

func (q *Queries) RescheduleOutbox(ctx context.Context, arg RescheduleOutboxParams) error {
	_, err := q.db.Exec(ctx, rescheduleOutbox, arg.ID, arg.NextAttemptAt, arg.LastError)
	return err
}
