// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const cancelPurchaseOrder = `-- name: CancelPurchaseOrder :exec
UPDATE purchase_orders
SET status = 'cancelled', cancelled_at = $3
WHERE tenant_id = $1 AND id = $2 AND status IN ('draft', 'sent')
`

type CancelPurchaseOrderParams struct {
	TenantID    uuid.UUID
	ID          uuid.UUID
	CancelledAt pgtype.Timestamptz
}

func (q *Queries) CancelPurchaseOrder(ctx context.Context, arg CancelPurchaseOrderParams) error {
	_, err := q.db.Exec(ctx, cancelPurchaseOrder, arg.TenantID, arg.ID, arg.CancelledAt)
	return err
}

const createPurchaseOrder = `-- name: CreatePurchaseOrder :one

INSERT INTO purchase_orders (id, tenant_id, supplier_id, note, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, supplier_id, status, expected_at, sent_at, received_at, cancelled_at, late_notified_at, note, created_by, created_at
`

type CreatePurchaseOrderParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	SupplierID uuid.UUID
	Note       string
	CreatedBy  uuid.NullUUID
}

// Заказы поставщику и приёмка (§5.4).
func (q *Queries) CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrder,
		arg.ID,
		arg.TenantID,
		arg.SupplierID,
		arg.Note,
		arg.CreatedBy,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SupplierID,
		&i.Status,
		&i.ExpectedAt,
		&i.SentAt,
		&i.ReceivedAt,
		&i.CancelledAt,
		&i.LateNotifiedAt,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deletePurchaseOrderLine = `-- name: DeletePurchaseOrderLine :exec
DELETE FROM purchase_order_lines
WHERE tenant_id = $1 AND order_id = $2 AND item_id = $3
`

type DeletePurchaseOrderLineParams struct {
	TenantID uuid.UUID
	OrderID  uuid.UUID
	ItemID   uuid.UUID
}

func (q *Queries) DeletePurchaseOrderLine(ctx context.Context, arg DeletePurchaseOrderLineParams) error {
	_, err := q.db.Exec(ctx, deletePurchaseOrderLine, arg.TenantID, arg.OrderID, arg.ItemID)
	return err
}

const getPurchaseOrder = `-- name: GetPurchaseOrder :one
SELECT id, tenant_id, supplier_id, status, expected_at, sent_at, received_at, cancelled_at, late_notified_at, note, created_by, created_at FROM purchase_orders WHERE tenant_id = $1 AND id = $2
`

type GetPurchaseOrderParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetPurchaseOrder(ctx context.Context, arg GetPurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrder, arg.TenantID, arg.ID)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SupplierID,
		&i.Status,
		&i.ExpectedAt,
		&i.SentAt,
		&i.ReceivedAt,
		&i.CancelledAt,
		&i.LateNotifiedAt,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPurchaseOrderForUpdate = `-- name: GetPurchaseOrderForUpdate :one
SELECT id, tenant_id, supplier_id, status, expected_at, sent_at, received_at, cancelled_at, late_notified_at, note, created_by, created_at FROM purchase_orders WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetPurchaseOrderForUpdateParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// Блокировка заказа: повторное нажатие «принять» не должно создать
// второй приход (FR-20).
func (q *Queries) GetPurchaseOrderForUpdate(ctx context.Context, arg GetPurchaseOrderForUpdateParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrderForUpdate, arg.TenantID, arg.ID)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SupplierID,
		&i.Status,
		&i.ExpectedAt,
		&i.SentAt,
		&i.ReceivedAt,
		&i.CancelledAt,
		&i.LateNotifiedAt,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const hasOpenOrderForSupplier = `-- name: HasOpenOrderForSupplier :one
SELECT EXISTS (
    SELECT 1 FROM purchase_orders
    WHERE tenant_id = $1 AND supplier_id = $2 AND status = 'sent' AND sent_at >= $3
) AS exists
`

type HasOpenOrderForSupplierParams struct {
	TenantID   uuid.UUID
	SupplierID uuid.UUID
	SentAt     pgtype.Timestamptz
}

// Напоминание до отсечки не шлётся, если заказ уже отправлен (§5.5).
func (q *Queries) HasOpenOrderForSupplier(ctx context.Context, arg HasOpenOrderForSupplierParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasOpenOrderForSupplier, arg.TenantID, arg.SupplierID, arg.SentAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listIncomingByItem = `-- name: ListIncomingByItem :many
SELECT
    l.item_id,
    o.expected_at,
    sum(l.qty_ordered)::numeric AS qty
FROM purchase_order_lines l
JOIN purchase_orders o ON o.tenant_id = l.tenant_id AND o.id = l.order_id
WHERE l.tenant_id = $1 AND o.status = 'sent'
GROUP BY l.item_id, o.expected_at
`

type ListIncomingByItemRow struct {
	ItemID     uuid.UUID
	ExpectedAt pgtype.Date
	Qty        decimal.Decimal
}

// «В пути»: количества по отправленным заказам с ожидаемой датой.
// Учитываются только заказы со статусом sent (§10.1, частичный индекс).
func (q *Queries) ListIncomingByItem(ctx context.Context, tenantID uuid.UUID) ([]ListIncomingByItemRow, error) {
	rows, err := q.db.Query(ctx, listIncomingByItem, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncomingByItemRow{}
	for rows.Next() {
		var i ListIncomingByItemRow
		if err := rows.Scan(&i.ItemID, &i.ExpectedAt, &i.Qty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingForItem = `-- name: ListIncomingForItem :many
SELECT
    o.expected_at,
    sum(l.qty_ordered)::numeric AS qty
FROM purchase_order_lines l
JOIN purchase_orders o ON o.tenant_id = l.tenant_id AND o.id = l.order_id
WHERE l.tenant_id = $1 AND l.item_id = $2 AND o.status = 'sent'
GROUP BY o.expected_at
`

type ListIncomingForItemParams struct {
	TenantID uuid.UUID
	ItemID   uuid.UUID
}

type ListIncomingForItemRow struct {
	ExpectedAt pgtype.Date
	Qty        decimal.Decimal
}

func (q *Queries) ListIncomingForItem(ctx context.Context, arg ListIncomingForItemParams) ([]ListIncomingForItemRow, error) {
	rows, err := q.db.Query(ctx, listIncomingForItem, arg.TenantID, arg.ItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncomingForItemRow{}
	for rows.Next() {
		var i ListIncomingForItemRow
		if err := rows.Scan(&i.ExpectedAt, &i.Qty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLateOrders = `-- name: ListLateOrders :many
SELECT o.id, o.tenant_id, o.supplier_id, o.status, o.expected_at, o.sent_at, o.received_at, o.cancelled_at, o.late_notified_at, o.note, o.created_by, o.created_at, s.name AS supplier_name
FROM purchase_orders o
JOIN suppliers s ON s.tenant_id = o.tenant_id AND s.id = o.supplier_id
WHERE o.tenant_id = $1
  AND o.status = 'sent'
  AND o.expected_at < $2
  AND o.late_notified_at IS NULL
`

type ListLateOrdersParams struct {
	TenantID uuid.UUID
	Today    pgtype.Date
}

type ListLateOrdersRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	SupplierID     uuid.UUID
	Status         PurchaseOrderStatus
	ExpectedAt     pgtype.Date
	SentAt         pgtype.Timestamptz
	ReceivedAt     pgtype.Timestamptz
	CancelledAt    pgtype.Timestamptz
	LateNotifiedAt pgtype.Timestamptz
	Note           string
	CreatedBy      uuid.NullUUID
	CreatedAt      pgtype.Timestamptz
	SupplierName   string
}

// Опоздания: к концу ожидаемого дня заказ не принят (FR-21).
func (q *Queries) ListLateOrders(ctx context.Context, arg ListLateOrdersParams) ([]ListLateOrdersRow, error) {
	rows, err := q.db.Query(ctx, listLateOrders, arg.TenantID, arg.Today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLateOrdersRow{}
	for rows.Next() {
		var i ListLateOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SupplierID,
			&i.Status,
			&i.ExpectedAt,
			&i.SentAt,
			&i.ReceivedAt,
			&i.CancelledAt,
			&i.LateNotifiedAt,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.SupplierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrderLines = `-- name: ListPurchaseOrderLines :many
SELECT
    l.tenant_id, l.order_id, l.item_id, l.qty_ordered, l.qty_received, l.purchase_unit, l.unit_factor, l.price,
    i.name AS item_name,
    i.base_unit
FROM purchase_order_lines l
JOIN items i ON i.tenant_id = l.tenant_id AND i.id = l.item_id
WHERE l.tenant_id = $1 AND l.order_id = $2
ORDER BY i.name
`

type ListPurchaseOrderLinesParams struct {
	TenantID uuid.UUID
	OrderID  uuid.UUID
}

type ListPurchaseOrderLinesRow struct {
	TenantID     uuid.UUID
	OrderID      uuid.UUID
	ItemID       uuid.UUID
	QtyOrdered   decimal.Decimal
	QtyReceived  decimal.NullDecimal
	PurchaseUnit string
	UnitFactor   decimal.Decimal
	Price        decimal.NullDecimal
	ItemName     string
	BaseUnit     string
}

func (q *Queries) ListPurchaseOrderLines(ctx context.Context, arg ListPurchaseOrderLinesParams) ([]ListPurchaseOrderLinesRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrderLines, arg.TenantID, arg.OrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchaseOrderLinesRow{}
	for rows.Next() {
		var i ListPurchaseOrderLinesRow
		if err := rows.Scan(
			&i.TenantID,
			&i.OrderID,
			&i.ItemID,
			&i.QtyOrdered,
			&i.QtyReceived,
			&i.PurchaseUnit,
			&i.UnitFactor,
			&i.Price,
			&i.ItemName,
			&i.BaseUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrders = `-- name: ListPurchaseOrders :many
SELECT
    o.id, o.tenant_id, o.supplier_id, o.status, o.expected_at, o.sent_at, o.received_at, o.cancelled_at, o.late_notified_at, o.note, o.created_by, o.created_at,
    s.name AS supplier_name
FROM purchase_orders o
JOIN suppliers s ON s.tenant_id = o.tenant_id AND s.id = o.supplier_id
WHERE o.tenant_id = $1
  AND ($3::purchase_order_status IS NULL OR o.status = $3)
ORDER BY o.created_at DESC
LIMIT $2
`

type ListPurchaseOrdersParams struct {
	TenantID uuid.UUID
	Limit    int32
	Status   *PurchaseOrderStatus
}

type ListPurchaseOrdersRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	SupplierID     uuid.UUID
	Status         PurchaseOrderStatus
	ExpectedAt     pgtype.Date
	SentAt         pgtype.Timestamptz
	ReceivedAt     pgtype.Timestamptz
	CancelledAt    pgtype.Timestamptz
	LateNotifiedAt pgtype.Timestamptz
	Note           string
	CreatedBy      uuid.NullUUID
	CreatedAt      pgtype.Timestamptz
	SupplierName   string
}

func (q *Queries) ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]ListPurchaseOrdersRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrders, arg.TenantID, arg.Limit, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchaseOrdersRow{}
	for rows.Next() {
		var i ListPurchaseOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SupplierID,
			&i.Status,
			&i.ExpectedAt,
			&i.SentAt,
			&i.ReceivedAt,
			&i.CancelledAt,
			&i.LateNotifiedAt,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.SupplierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderLateNotified = `-- name: MarkOrderLateNotified :exec
UPDATE purchase_orders SET late_notified_at = $3 WHERE tenant_id = $1 AND id = $2
`

type MarkOrderLateNotifiedParams struct {
	TenantID       uuid.UUID
	ID             uuid.UUID
	LateNotifiedAt pgtype.Timestamptz
}

func (q *Queries) MarkOrderLateNotified(ctx context.Context, arg MarkOrderLateNotifiedParams) error {
	_, err := q.db.Exec(ctx, markOrderLateNotified, arg.TenantID, arg.ID, arg.LateNotifiedAt)
	return err
}

const receivePurchaseOrder = `-- name: ReceivePurchaseOrder :exec
UPDATE purchase_orders
SET status = 'received', received_at = $3
WHERE tenant_id = $1 AND id = $2 AND status = 'sent'
`

type ReceivePurchaseOrderParams struct {
	TenantID   uuid.UUID
	ID         uuid.UUID
	ReceivedAt pgtype.Timestamptz
}

func (q *Queries) ReceivePurchaseOrder(ctx context.Context, arg ReceivePurchaseOrderParams) error {
	_, err := q.db.Exec(ctx, receivePurchaseOrder, arg.TenantID, arg.ID, arg.ReceivedAt)
	return err
}

const sendPurchaseOrder = `-- name: SendPurchaseOrder :exec
UPDATE purchase_orders
SET status = 'sent', sent_at = $3, expected_at = $4
WHERE tenant_id = $1 AND id = $2 AND status = 'draft'
`

type SendPurchaseOrderParams struct {
	TenantID   uuid.UUID
	ID         uuid.UUID
	SentAt     pgtype.Timestamptz
	ExpectedAt pgtype.Date
}

func (q *Queries) SendPurchaseOrder(ctx context.Context, arg SendPurchaseOrderParams) error {
	_, err := q.db.Exec(ctx, sendPurchaseOrder,
		arg.TenantID,
		arg.ID,
		arg.SentAt,
		arg.ExpectedAt,
	)
	return err
}

const setPurchaseOrderLineReceived = `-- name: SetPurchaseOrderLineReceived :exec
UPDATE purchase_order_lines
SET qty_received = $4
WHERE tenant_id = $1 AND order_id = $2 AND item_id = $3
`

type SetPurchaseOrderLineReceivedParams struct {
	TenantID    uuid.UUID
	OrderID     uuid.UUID
	ItemID      uuid.UUID
	QtyReceived decimal.NullDecimal
}

func (q *Queries) SetPurchaseOrderLineReceived(ctx context.Context, arg SetPurchaseOrderLineReceivedParams) error {
	_, err := q.db.Exec(ctx, setPurchaseOrderLineReceived,
		arg.TenantID,
		arg.OrderID,
		arg.ItemID,
		arg.QtyReceived,
	)
	return err
}

const upsertPurchaseOrderLine = `-- name: UpsertPurchaseOrderLine :exec
INSERT INTO purchase_order_lines (
    tenant_id, order_id, item_id, qty_ordered, purchase_unit, unit_factor, price
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (order_id, item_id) DO UPDATE SET
    qty_ordered   = EXCLUDED.qty_ordered,
    purchase_unit = EXCLUDED.purchase_unit,
    unit_factor   = EXCLUDED.unit_factor,
    price         = EXCLUDED.price
`

type UpsertPurchaseOrderLineParams struct {
	TenantID     uuid.UUID
	OrderID      uuid.UUID
	ItemID       uuid.UUID
	QtyOrdered   decimal.Decimal
	PurchaseUnit string
	UnitFactor   decimal.Decimal
	Price        decimal.NullDecimal
}

func (q *Queries) UpsertPurchaseOrderLine(ctx context.Context, arg UpsertPurchaseOrderLineParams) error {
	_, err := q.db.Exec(ctx, upsertPurchaseOrderLine,
		arg.TenantID,
		arg.OrderID,
		arg.ItemID,
		arg.QtyOrdered,
		arg.PurchaseUnit,
		arg.UnitFactor,
		arg.Price,
	)
	return err
}
