// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Querier interface {
	AdvanceTenantClock(ctx context.Context, arg AdvanceTenantClockParams) (pgtype.Interval, error)
	// Шаг 3: остаток меняется в той же транзакции, что и движение.
	// CHECK (on_hand >= 0) — последний рубеж, если проверка в коде даст сбой.
	ApplyMovementToBalance(ctx context.Context, arg ApplyMovementToBalanceParams) (decimal.Decimal, error)
	// Позиция не удаляется, а архивируется (FR-1): её движения остаются в журнале.
	ArchiveItem(ctx context.Context, arg ArchiveItemParams) error
	ArchiveSupplier(ctx context.Context, arg ArchiveSupplierParams) error
	// Пакетная вставка истории для генератора песочницы (§7.1).
	//
	// В ТЗ на этом месте COPY, но PostgreSQL не поддерживает COPY FROM для
	// таблиц с row-level security (ADR-005). Разворот массивов даёт тот же
	// один заход в базу и сохраняет RLS: политика проверяется как на INSERT.
	BulkInsertMovements(ctx context.Context, arg BulkInsertMovementsParams) (int64, error)
	// Ночной пересчёт переписывает ряд целиком: у 40 позиций за 90 дней это
	// 3600 строк, и поштучные запросы не укладываются в бюджет задачи (§12).
	BulkUpsertDailyConsumption(ctx context.Context, arg BulkUpsertDailyConsumptionParams) (int64, error)
	BulkUpsertForecasts(ctx context.Context, arg BulkUpsertForecastsParams) (int64, error)
	CancelPurchaseOrder(ctx context.Context, arg CancelPurchaseOrderParams) error
	// Воркер забирает пачку. SKIP LOCKED позволяет нескольким воркерам работать
	// параллельно, не дожидаясь друг друга (ADR-004).
	ClaimOutbox(ctx context.Context, arg ClaimOutboxParams) ([]Outbox, error)
	ClearUserTelegramChatID(ctx context.Context, telegramChatID *int64) error
	CountActiveSandboxes(ctx context.Context, expiresAt pgtype.Timestamptz) (int32, error)
	CountPendingOutbox(ctx context.Context) (int32, error)
	CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int32, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	// Заказы поставщику и приёмка (§5.4).
	CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	// --- инвентаризация ---
	CreateStockCount(ctx context.Context, arg CreateStockCountParams) (StockCount, error)
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	CreateTelegramLinkCode(ctx context.Context, arg CreateTelegramLinkCodeParams) error
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (Warehouse, error)
	// Дашборд собирается одним запросом (§9.2, исключение из правила
	// «не ходить в чужие таблицы»): экран должен отвечать за 300 мс на 300 позициях.
	Dashboard(ctx context.Context, tenantID uuid.UUID) ([]DashboardRow, error)
	DeleteDailyConsumptionBefore(ctx context.Context, arg DeleteDailyConsumptionBeforeParams) (int64, error)
	DeleteExpiredSessions(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error)
	DeleteExpiredTelegramLinkCodes(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error)
	// Прогноз, метрики и read-модель статусов (§4, §5.3).
	// Ночной пересчёт идемпотентен: старый горизонт сносится целиком,
	// потом пишется новый (§4.4).
	DeleteForecastsFrom(ctx context.Context, arg DeleteForecastsFromParams) (int64, error)
	// Снос старого горизонта у позиций без модели одним запросом.
	DeleteForecastsFromForItems(ctx context.Context, arg DeleteForecastsFromForItemsParams) (int64, error)
	DeletePurchaseOrderLine(ctx context.Context, arg DeletePurchaseOrderLineParams) error
	DeleteSession(ctx context.Context, tokenHash []byte) error
	// Удаление каскадом уносит всё содержимое тенанта.
	DeleteTenant(ctx context.Context, id uuid.UUID) error
	DeleteUserSessions(ctx context.Context, userID uuid.UUID) error
	// Строка остатка заводится при создании позиции; здесь — страховка на случай,
	// когда позиция появилась в обход обычного пути (импорт, генератор).
	EnsureBalance(ctx context.Context, arg EnsureBalanceParams) error
	GetBalance(ctx context.Context, arg GetBalanceParams) (StockBalance, error)
	GetCategoryByName(ctx context.Context, arg GetCategoryByNameParams) (Category, error)
	// В MVP у организации один склад (§1, допущения).
	GetDefaultWarehouse(ctx context.Context, tenantID uuid.UUID) (Warehouse, error)
	GetForecastMetrics(ctx context.Context, arg GetForecastMetricsParams) (ForecastMetric, error)
	GetItem(ctx context.Context, arg GetItemParams) (Item, error)
	GetItemByName(ctx context.Context, arg GetItemByNameParams) (Item, error)
	// Всё, что нужно расчёту статуса одной позиции, одной строкой:
	// параметры позиции, условия поставщика, остаток и σ из бэктеста.
	GetItemForStatus(ctx context.Context, arg GetItemForStatusParams) (GetItemForStatusRow, error)
	GetItemStatus(ctx context.Context, arg GetItemStatusParams) (ItemStatus, error)
	GetMovement(ctx context.Context, arg GetMovementParams) (StockMovement, error)
	// Движения, остатки и инвентаризация (§3.3–3.5).
	//
	// stock_movements только дописывается: права на UPDATE и DELETE у роли
	// приложения отозваны (ADR-002). Исправление ошибки — сторно.
	// Шаг 1 записи движения: повтор формы с тем же ключом возвращает уже
	// созданное движение и не создаёт второго (FR-10).
	GetMovementByIdempotencyKey(ctx context.Context, arg GetMovementByIdempotencyKeyParams) (StockMovement, error)
	GetPurchaseOrder(ctx context.Context, arg GetPurchaseOrderParams) (PurchaseOrder, error)
	// Блокировка заказа: повторное нажатие «принять» не должно создать
	// второй приход (FR-20).
	GetPurchaseOrderForUpdate(ctx context.Context, arg GetPurchaseOrderForUpdateParams) (PurchaseOrder, error)
	// Сторно возможно один раз (FR-7): проверяем, не сторнировали ли уже.
	GetReversalOf(ctx context.Context, arg GetReversalOfParams) (StockMovement, error)
	// Кросс-тенантный: тенант определяется как раз по сессии.
	// Отдаёт сразу и пользователя, чтобы не ходить в БД дважды на каждый запрос.
	GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error)
	GetStockCount(ctx context.Context, arg GetStockCountParams) (StockCount, error)
	// Блокировка документа: повторное нажатие «провести» не должно создать
	// вторую пачку корректировок.
	GetStockCountForUpdate(ctx context.Context, arg GetStockCountForUpdateParams) (StockCount, error)
	GetSupplier(ctx context.Context, arg GetSupplierParams) (Supplier, error)
	GetSupplierByName(ctx context.Context, arg GetSupplierByNameParams) (Supplier, error)
	GetSupplierItem(ctx context.Context, arg GetSupplierItemParams) (SupplierItem, error)
	// Условия закупки у поставщика по умолчанию — их и берёт расчёт заказа.
	GetSupplierItemForItem(ctx context.Context, arg GetSupplierItemForItemParams) (SupplierItem, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	// Запросы входа и сессий.
	//
	// Часть из них выполняется от обслуживающей роли (BYPASSRLS): в момент входа
	// и разбора сессии тенант ещё не известен (ADR-005). Такие запросы помечены
	// в комментарии.
	// Кросс-тенантный: email уникален глобально. Только обслуживающая роль.
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// Напоминание до отсечки не шлётся, если заказ уже отправлен (§5.5).
	HasOpenOrderForSupplier(ctx context.Context, arg HasOpenOrderForSupplierParams) (bool, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertMovement(ctx context.Context, arg InsertMovementParams) (StockMovement, error)
	// Лента, transactional outbox и журнал аудита (§5.5, ADR-004).
	// Дедупликация уникальным индексом по (tenant_id, dedup_key):
	// повтор молча не создаёт вторую запись.
	InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error)
	InsertOutbox(ctx context.Context, arg InsertOutboxParams) error
	// График спроса: фактический расход за N дней (§6.2).
	ItemHistory(ctx context.Context, arg ItemHistoryParams) ([]ItemHistoryRow, error)
	// Карточка позиции: параметры, статус, объяснение и точность (§6.2).
	ItemInsights(ctx context.Context, arg ItemInsightsParams) (ItemInsightsRow, error)
	ListActiveItemIDs(ctx context.Context, tenantID uuid.UUID) ([]uuid.UUID, error)
	// Обход тенантов ночными задачами. Истёкшие песочницы пропускаются:
	// их всё равно вот-вот удалит очистка.
	ListActiveTenants(ctx context.Context, expiresAt pgtype.Timestamptz) ([]Tenant, error)
	ListBalances(ctx context.Context, tenantID uuid.UUID) ([]StockBalance, error)
	// Номенклатура, категории и поставщики (§3.1, §3.2).
	//
	// Везде есть tenant_id: RLS уже отсечёт чужое, но явный предикат нужен
	// планировщику — tenant_id стоит первым в составных индексах.
	ListCategories(ctx context.Context, tenantID uuid.UUID) ([]Category, error)
	// Сырые движения расхода для сборки ряда (§4.1).
	//
	// Отдаются по одному, а не агрегатом по дням, потому что корректировки
	// из пересчёта нужно размазать по интервалу между пересчётами: в режиме
	// «только пересчёт» весь расход за несколько дней записан одним движением.
	// Сторнированные движения и сами сторно в ряд не попадают.
	ListConsumptionMovementsForSeries(ctx context.Context, arg ListConsumptionMovementsForSeriesParams) ([]ListConsumptionMovementsForSeriesRow, error)
	// При проведении берутся только строки с внесённым фактом.
	ListCountedLines(ctx context.Context, arg ListCountedLinesParams) ([]StockCountLine, error)
	ListDailyConsumption(ctx context.Context, arg ListDailyConsumptionParams) ([]DailyConsumption, error)
	// Сборка дневного расхода (§4.1): расход, списания и корректировки с обратным
	// знаком, в календарных днях часового пояса тенанта.
	// Сторнированные движения и сами сторно из ряда исключаются.
	ListDailyConsumptionSource(ctx context.Context, arg ListDailyConsumptionSourceParams) ([]ListDailyConsumptionSourceRow, error)
	// «Нет данных ≠ ноль»: день считается «с данными», если в тенанте был хотя бы
	// один расход или пересчёт (§4.1).
	ListDaysWithActivity(ctx context.Context, arg ListDaysWithActivityParams) ([]pgtype.Date, error)
	// День «с данными»: был хотя бы один расход или проведённый пересчёт (§4.1).
	ListDaysWithUsage(ctx context.Context, arg ListDaysWithUsageParams) ([]pgtype.Date, error)
	// Очистка песочниц: раз в час, пачками, чтобы не блокировать БД (§7.5).
	ListExpiredSandboxes(ctx context.Context, arg ListExpiredSandboxesParams) ([]uuid.UUID, error)
	ListForecastForItem(ctx context.Context, arg ListForecastForItemParams) ([]ListForecastForItemRow, error)
	ListForecastMetrics(ctx context.Context, tenantID uuid.UUID) ([]ForecastMetric, error)
	// Пакетная версия для ночного пересчёта статусов: один запрос на тенанта
	// вместо запроса на позицию.
	ListForecastsFrom(ctx context.Context, arg ListForecastsFromParams) ([]ListForecastsFromRow, error)
	// «В пути»: количества по отправленным заказам с ожидаемой датой.
	// Учитываются только заказы со статусом sent (§10.1, частичный индекс).
	ListIncomingByItem(ctx context.Context, tenantID uuid.UUID) ([]ListIncomingByItemRow, error)
	ListIncomingForItem(ctx context.Context, arg ListIncomingForItemParams) ([]ListIncomingForItemRow, error)
	ListItemStatuses(ctx context.Context, tenantID uuid.UUID) ([]ItemStatus, error)
	// Таблица позиций дашборда: до 500 строк без пагинации (§6.1).
	ListItems(ctx context.Context, arg ListItemsParams) ([]ListItemsRow, error)
	// Пакетная версия для ночного пересчёта.
	ListItemsForStatus(ctx context.Context, tenantID uuid.UUID) ([]ListItemsForStatusRow, error)
	// Опоздания: к концу ожидаемого дня заказ не принят (FR-21).
	ListLateOrders(ctx context.Context, arg ListLateOrdersParams) ([]ListLateOrdersRow, error)
	// Журнал с фильтрами и курсорной пагинацией (FR-11).
	// Курсор — пара (occurred_at, id): id разводит движения одной секунды.
	ListMovements(ctx context.Context, arg ListMovementsParams) ([]ListMovementsRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListPurchaseOrderLines(ctx context.Context, arg ListPurchaseOrderLinesParams) ([]ListPurchaseOrderLinesRow, error)
	ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]ListPurchaseOrdersRow, error)
	// Кому слать: владельцу — сводки и алерты, сотруднику — только лента.
	ListRecipients(ctx context.Context, tenantID uuid.UUID) ([]ListRecipientsRow, error)
	// Расхождение показывается до проведения: сравниваем внесённый факт
	// с учётом на момент открытия документа и с текущим остатком (FR-13).
	ListStockCountLines(ctx context.Context, arg ListStockCountLinesParams) ([]ListStockCountLinesRow, error)
	ListStockCounts(ctx context.Context, arg ListStockCountsParams) ([]StockCount, error)
	// Дни, когда остаток доходил до нуля: модель не должна учиться на заниженных
	// цифрах (§4.1). Остаток восстанавливается из журнала нарастающим итогом.
	ListStockoutDays(ctx context.Context, arg ListStockoutDaysParams) ([]ListStockoutDaysRow, error)
	ListSupplierItems(ctx context.Context, arg ListSupplierItemsParams) ([]SupplierItem, error)
	ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error)
	ListUsers(ctx context.Context, tenantID uuid.UUID) ([]User, error)
	ListWarehouses(ctx context.Context, tenantID uuid.UUID) ([]Warehouse, error)
	// Шаг 2: блокируем строку остатка. Конкурентные списания одной позиции идут
	// по очереди, поэтому проверка «не уйдём ли в минус» честная (§10.2).
	LockBalance(ctx context.Context, arg LockBalanceParams) (decimal.Decimal, error)
	MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) (int64, error)
	MarkOrderLateNotified(ctx context.Context, arg MarkOrderLateNotifiedParams) error
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error
	MarkOutboxSent(ctx context.Context, arg MarkOutboxSentParams) error
	PostStockCount(ctx context.Context, arg PostStockCountParams) error
	ReceivePurchaseOrder(ctx context.Context, arg ReceivePurchaseOrderParams) error
	RescheduleOutbox(ctx context.Context, arg RescheduleOutboxParams) error
	ResetTenantClock(ctx context.Context, id uuid.UUID) error
	SendPurchaseOrder(ctx context.Context, arg SendPurchaseOrderParams) error
	SetPurchaseOrderLineReceived(ctx context.Context, arg SetPurchaseOrderLineReceivedParams) error
	SetTenantAutopilot(ctx context.Context, arg SetTenantAutopilotParams) error
	SetUserTelegramChatID(ctx context.Context, arg SetUserTelegramChatIDParams) error
	// Блок «Заказать сегодня», сгруппированный по поставщикам (§6).
	Suggestions(ctx context.Context, tenantID uuid.UUID) ([]SuggestionsRow, error)
	SumConsumptionByItemForDay(ctx context.Context, arg SumConsumptionByItemForDayParams) ([]SumConsumptionByItemForDayRow, error)
	// Сколько уже израсходовано сегодня: за сегодняшний день в целевой уровень
	// идёт только неизрасходованная часть прогноза (§5.2).
	SumConsumptionForDay(ctx context.Context, arg SumConsumptionForDayParams) (decimal.Decimal, error)
	// Ночная сверка (FR-17): остаток обязан совпадать с суммой движений.
	SumMovementsByItem(ctx context.Context, tenantID uuid.UUID) ([]SumMovementsByItemRow, error)
	// Продление срока сессии; last_seen_at заодно показывает активность.
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
	// COALESCE позволяет прислать только изменённые поля (PATCH).
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error)
	UpdateTenantSettings(ctx context.Context, arg UpdateTenantSettingsParams) error
	UpsertDailyConsumption(ctx context.Context, arg UpsertDailyConsumptionParams) error
	UpsertForecast(ctx context.Context, arg UpsertForecastParams) error
	UpsertForecastMetrics(ctx context.Context, arg UpsertForecastMetricsParams) error
	UpsertItemStatus(ctx context.Context, arg UpsertItemStatusParams) error
	UpsertPurchaseOrderLine(ctx context.Context, arg UpsertPurchaseOrderLineParams) error
	UpsertStockCountLine(ctx context.Context, arg UpsertStockCountLineParams) error
	UpsertSupplierItem(ctx context.Context, arg UpsertSupplierItemParams) (SupplierItem, error)
	// Код одноразовый: помечаем использованным той же командой, что и читаем.
	UseTelegramLinkCode(ctx context.Context, arg UseTelegramLinkCodeParams) (UseTelegramLinkCodeRow, error)
}

var _ Querier = (*Queries)(nil)
