// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sandbox.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const guideState = `-- name: GuideState :one

SELECT
    (SELECT count(*) FROM suppliers s
      WHERE s.tenant_id = t.id AND s.archived_at IS NULL)::int AS suppliers,
    (SELECT count(*) FROM items i
      WHERE i.tenant_id = t.id AND i.archived_at IS NULL)::int AS items,
    -- Прогнозу нужна история: считаем разные дни с расходом.
    (SELECT count(DISTINCT (m.occurred_at AT TIME ZONE t.timezone)::date)
       FROM stock_movements m
      WHERE m.tenant_id = t.id AND m.type = 'usage')::int AS usage_days,
    (SELECT count(*) FROM stock_counts c
      WHERE c.tenant_id = t.id AND c.status = 'posted')::int AS posted_counts,
    (SELECT count(*) FROM forecast_metrics f
      WHERE f.tenant_id = t.id)::int AS forecasts,
    (SELECT count(*) FROM purchase_orders o
      WHERE o.tenant_id = t.id AND o.status IN ('sent', 'received'))::int AS sent_orders,
    (SELECT count(*) FROM purchase_orders o
      WHERE o.tenant_id = t.id AND o.status = 'received')::int AS received_orders,
    (extract(epoch FROM t.clock_offset) / 86400)::int AS virtual_days,
    (SELECT count(*) FROM notifications n
      WHERE n.tenant_id = t.id AND n.read_at IS NOT NULL)::int AS read_notifications
FROM tenants t
WHERE t.id = $1
`

type GuideStateRow struct {
	Suppliers         int32
	Items             int32
	UsageDays         int32
	PostedCounts      int32
	Forecasts         int32
	SentOrders        int32
	ReceivedOrders    int32
	VirtualDays       int32
	ReadNotifications int32
}

// Пошаговое демо (§7): состояние шагов и защита наполнения.
// По одному числу на шаг. Шаг выполнен, когда в данных есть его след, а
// не когда нажата кнопка: ручной путь и шаблон засчитываются одинаково.
func (q *Queries) GuideState(ctx context.Context, tenantID uuid.UUID) (GuideStateRow, error) {
	row := q.db.QueryRow(ctx, guideState, tenantID)
	var i GuideStateRow
	err := row.Scan(
		&i.Suppliers,
		&i.Items,
		&i.UsageDays,
		&i.PostedCounts,
		&i.Forecasts,
		&i.SentOrders,
		&i.ReceivedOrders,
		&i.VirtualDays,
		&i.ReadNotifications,
	)
	return i, err
}

const guideUnlock = `-- name: GuideUnlock :exec
SELECT pg_advisory_unlock(hashtextextended('sandbox-guide:' || $1::text, 0))
`

func (q *Queries) GuideUnlock(ctx context.Context, tenantID string) error {
	_, err := q.db.Exec(ctx, guideUnlock, tenantID)
	return err
}

const itemsWithMovementsBefore = `-- name: ItemsWithMovementsBefore :many
SELECT DISTINCT item_id FROM stock_movements
WHERE tenant_id = $1 AND occurred_at < $2
`

type ItemsWithMovementsBeforeParams struct {
	TenantID uuid.UUID
	Before   pgtype.Timestamptz
}

// Позиции, у которых уже есть движения раньше указанного момента: историю
// им генератор второй раз не дописывает.
func (q *Queries) ItemsWithMovementsBefore(ctx context.Context, arg ItemsWithMovementsBeforeParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, itemsWithMovementsBefore, arg.TenantID, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var item_id uuid.UUID
		if err := rows.Scan(&item_id); err != nil {
			return nil, err
		}
		items = append(items, item_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryGuideLock = `-- name: TryGuideLock :one
SELECT pg_try_advisory_lock(hashtextextended('sandbox-guide:' || $1::text, 0))::boolean
`

// Сессионная блокировка на тенанта: два наполнения одного демо сразу
// создали бы дубли. Снимается GuideUnlock на том же соединении.
func (q *Queries) TryGuideLock(ctx context.Context, tenantID string) (bool, error) {
	row := q.db.QueryRow(ctx, tryGuideLock, tenantID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
