// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const applyMovementToBalance = `-- name: ApplyMovementToBalance :one
UPDATE stock_balances
SET on_hand = on_hand + $3::numeric, updated_at = $4
WHERE warehouse_id = $1 AND item_id = $2
RETURNING on_hand
`

type ApplyMovementToBalanceParams struct {
	WarehouseID uuid.UUID
	ItemID      uuid.UUID
	Delta       decimal.Decimal
	Now         pgtype.Timestamptz
}

// Шаг 3: остаток меняется в той же транзакции, что и движение.
// CHECK (on_hand >= 0) — последний рубеж, если проверка в коде даст сбой.
func (q *Queries) ApplyMovementToBalance(ctx context.Context, arg ApplyMovementToBalanceParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, applyMovementToBalance,
		arg.WarehouseID,
		arg.ItemID,
		arg.Delta,
		arg.Now,
	)
	var on_hand decimal.Decimal
	err := row.Scan(&on_hand)
	return on_hand, err
}

const bulkInsertMovements = `-- name: BulkInsertMovements :execrows
INSERT INTO stock_movements (
    id, tenant_id, warehouse_id, item_id, type, qty,
    occurred_at, created_by, reason, comment
)
SELECT
    m.id,
    $1::uuid,
    $2::uuid,
    m.item_id,
    m.type,
    m.qty,
    m.occurred_at,
    $3::uuid,
    -- Пустая строка означает «причины нет»: text[] не хранит NULL удобно.
    nullif(m.reason, ''),
    m.comment
FROM (
    SELECT
        unnest($4::uuid[])            AS id,
        unnest($5::uuid[])       AS item_id,
        -- Типы идут как text[]: pgx не кодирует срез пользовательского
        -- enum-типа, а приведение делает база.
        unnest($6::text[])::movement_type AS type,
        unnest($7::numeric[])  AS qty,
        unnest($8::timestamptz[]) AS occurred_at,
        unnest($9::text[])        AS reason,
        unnest($10::text[])       AS comment
) AS m
`

type BulkInsertMovementsParams struct {
	TenantID    uuid.UUID
	WarehouseID uuid.UUID
	CreatedBy   uuid.UUID
	Ids         []uuid.UUID
	ItemIds     []uuid.UUID
	Types       []string
	Quantities  []decimal.Decimal
	OccurredAts []pgtype.Timestamptz
	Reasons     []string
	Comments    []string
}

// Пакетная вставка истории для генератора песочницы (§7.1).
//
// В ТЗ на этом месте COPY, но PostgreSQL не поддерживает COPY FROM для
// таблиц с row-level security (ADR-005). Разворот массивов даёт тот же
// один заход в базу и сохраняет RLS: политика проверяется как на INSERT.
func (q *Queries) BulkInsertMovements(ctx context.Context, arg BulkInsertMovementsParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkInsertMovements,
		arg.TenantID,
		arg.WarehouseID,
		arg.CreatedBy,
		arg.Ids,
		arg.ItemIds,
		arg.Types,
		arg.Quantities,
		arg.OccurredAts,
		arg.Reasons,
		arg.Comments,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createStockCount = `-- name: CreateStockCount :one

INSERT INTO stock_counts (id, tenant_id, warehouse_id, scope, note, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, warehouse_id, status, scope, note, created_by, posted_by, posted_at, created_at
`

type CreateStockCountParams struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	WarehouseID uuid.UUID
	Scope       string
	Note        string
	CreatedBy   uuid.NullUUID
}

// --- инвентаризация ---
func (q *Queries) CreateStockCount(ctx context.Context, arg CreateStockCountParams) (StockCount, error) {
	row := q.db.QueryRow(ctx, createStockCount,
		arg.ID,
		arg.TenantID,
		arg.WarehouseID,
		arg.Scope,
		arg.Note,
		arg.CreatedBy,
	)
	var i StockCount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WarehouseID,
		&i.Status,
		&i.Scope,
		&i.Note,
		&i.CreatedBy,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDailyConsumptionBefore = `-- name: DeleteDailyConsumptionBefore :execrows
DELETE FROM daily_consumption WHERE tenant_id = $1 AND day < $2
`

type DeleteDailyConsumptionBeforeParams struct {
	TenantID uuid.UUID
	Day      pgtype.Date
}

func (q *Queries) DeleteDailyConsumptionBefore(ctx context.Context, arg DeleteDailyConsumptionBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDailyConsumptionBefore, arg.TenantID, arg.Day)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureBalance = `-- name: EnsureBalance :exec
INSERT INTO stock_balances (tenant_id, warehouse_id, item_id, on_hand)
VALUES ($1, $2, $3, 0)
ON CONFLICT (warehouse_id, item_id) DO NOTHING
`

type EnsureBalanceParams struct {
	TenantID    uuid.UUID
	WarehouseID uuid.UUID
	ItemID      uuid.UUID
}

// Строка остатка заводится при создании позиции; здесь — страховка на случай,
// когда позиция появилась в обход обычного пути (импорт, генератор).
func (q *Queries) EnsureBalance(ctx context.Context, arg EnsureBalanceParams) error {
	_, err := q.db.Exec(ctx, ensureBalance, arg.TenantID, arg.WarehouseID, arg.ItemID)
	return err
}

const getBalance = `-- name: GetBalance :one
SELECT tenant_id, warehouse_id, item_id, on_hand, updated_at FROM stock_balances WHERE tenant_id = $1 AND item_id = $2
`

type GetBalanceParams struct {
	TenantID uuid.UUID
	ItemID   uuid.UUID
}

func (q *Queries) GetBalance(ctx context.Context, arg GetBalanceParams) (StockBalance, error) {
	row := q.db.QueryRow(ctx, getBalance, arg.TenantID, arg.ItemID)
	var i StockBalance
	err := row.Scan(
		&i.TenantID,
		&i.WarehouseID,
		&i.ItemID,
		&i.OnHand,
		&i.UpdatedAt,
	)
	return i, err
}

const getMovement = `-- name: GetMovement :one
SELECT id, tenant_id, warehouse_id, item_id, type, qty, occurred_at, created_at, created_by, reason, comment, order_id, count_id, reverses_id, idempotency_key FROM stock_movements WHERE tenant_id = $1 AND id = $2
`

type GetMovementParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetMovement(ctx context.Context, arg GetMovementParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, getMovement, arg.TenantID, arg.ID)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WarehouseID,
		&i.ItemID,
		&i.Type,
		&i.Qty,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Reason,
		&i.Comment,
		&i.OrderID,
		&i.CountID,
		&i.ReversesID,
		&i.IdempotencyKey,
	)
	return i, err
}

const getMovementByIdempotencyKey = `-- name: GetMovementByIdempotencyKey :one

SELECT id, tenant_id, warehouse_id, item_id, type, qty, occurred_at, created_at, created_by, reason, comment, order_id, count_id, reverses_id, idempotency_key FROM stock_movements
WHERE tenant_id = $1 AND idempotency_key = $2
`

type GetMovementByIdempotencyKeyParams struct {
	TenantID       uuid.UUID
	IdempotencyKey *string
}

// Движения, остатки и инвентаризация (§3.3–3.5).
//
// stock_movements только дописывается: права на UPDATE и DELETE у роли
// приложения отозваны (ADR-002). Исправление ошибки — сторно.
// Шаг 1 записи движения: повтор формы с тем же ключом возвращает уже
// созданное движение и не создаёт второго (FR-10).
func (q *Queries) GetMovementByIdempotencyKey(ctx context.Context, arg GetMovementByIdempotencyKeyParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, getMovementByIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WarehouseID,
		&i.ItemID,
		&i.Type,
		&i.Qty,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Reason,
		&i.Comment,
		&i.OrderID,
		&i.CountID,
		&i.ReversesID,
		&i.IdempotencyKey,
	)
	return i, err
}

const getReversalOf = `-- name: GetReversalOf :one
SELECT id, tenant_id, warehouse_id, item_id, type, qty, occurred_at, created_at, created_by, reason, comment, order_id, count_id, reverses_id, idempotency_key FROM stock_movements
WHERE tenant_id = $1 AND reverses_id = $2
`

type GetReversalOfParams struct {
	TenantID   uuid.UUID
	ReversesID uuid.NullUUID
}

// Сторно возможно один раз (FR-7): проверяем, не сторнировали ли уже.
func (q *Queries) GetReversalOf(ctx context.Context, arg GetReversalOfParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, getReversalOf, arg.TenantID, arg.ReversesID)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WarehouseID,
		&i.ItemID,
		&i.Type,
		&i.Qty,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Reason,
		&i.Comment,
		&i.OrderID,
		&i.CountID,
		&i.ReversesID,
		&i.IdempotencyKey,
	)
	return i, err
}

const getStockCount = `-- name: GetStockCount :one
SELECT id, tenant_id, warehouse_id, status, scope, note, created_by, posted_by, posted_at, created_at FROM stock_counts WHERE tenant_id = $1 AND id = $2
`

type GetStockCountParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetStockCount(ctx context.Context, arg GetStockCountParams) (StockCount, error) {
	row := q.db.QueryRow(ctx, getStockCount, arg.TenantID, arg.ID)
	var i StockCount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WarehouseID,
		&i.Status,
		&i.Scope,
		&i.Note,
		&i.CreatedBy,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStockCountForUpdate = `-- name: GetStockCountForUpdate :one
SELECT id, tenant_id, warehouse_id, status, scope, note, created_by, posted_by, posted_at, created_at FROM stock_counts WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetStockCountForUpdateParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// Блокировка документа: повторное нажатие «провести» не должно создать
// вторую пачку корректировок.
func (q *Queries) GetStockCountForUpdate(ctx context.Context, arg GetStockCountForUpdateParams) (StockCount, error) {
	row := q.db.QueryRow(ctx, getStockCountForUpdate, arg.TenantID, arg.ID)
	var i StockCount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WarehouseID,
		&i.Status,
		&i.Scope,
		&i.Note,
		&i.CreatedBy,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertMovement = `-- name: InsertMovement :one
INSERT INTO stock_movements (
    id, tenant_id, warehouse_id, item_id, type, qty,
    occurred_at, created_by, reason, comment,
    order_id, count_id, reverses_id, idempotency_key
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, tenant_id, warehouse_id, item_id, type, qty, occurred_at, created_at, created_by, reason, comment, order_id, count_id, reverses_id, idempotency_key
`

type InsertMovementParams struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	WarehouseID    uuid.UUID
	ItemID         uuid.UUID
	Type           MovementType
	Qty            decimal.Decimal
	OccurredAt     pgtype.Timestamptz
	CreatedBy      uuid.NullUUID
	Reason         *string
	Comment        string
	OrderID        uuid.NullUUID
	CountID        uuid.NullUUID
	ReversesID     uuid.NullUUID
	IdempotencyKey *string
}

func (q *Queries) InsertMovement(ctx context.Context, arg InsertMovementParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, insertMovement,
		arg.ID,
		arg.TenantID,
		arg.WarehouseID,
		arg.ItemID,
		arg.Type,
		arg.Qty,
		arg.OccurredAt,
		arg.CreatedBy,
		arg.Reason,
		arg.Comment,
		arg.OrderID,
		arg.CountID,
		arg.ReversesID,
		arg.IdempotencyKey,
	)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WarehouseID,
		&i.ItemID,
		&i.Type,
		&i.Qty,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Reason,
		&i.Comment,
		&i.OrderID,
		&i.CountID,
		&i.ReversesID,
		&i.IdempotencyKey,
	)
	return i, err
}

const listBalances = `-- name: ListBalances :many
SELECT tenant_id, warehouse_id, item_id, on_hand, updated_at FROM stock_balances WHERE tenant_id = $1
`

func (q *Queries) ListBalances(ctx context.Context, tenantID uuid.UUID) ([]StockBalance, error) {
	rows, err := q.db.Query(ctx, listBalances, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockBalance{}
	for rows.Next() {
		var i StockBalance
		if err := rows.Scan(
			&i.TenantID,
			&i.WarehouseID,
			&i.ItemID,
			&i.OnHand,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountedLines = `-- name: ListCountedLines :many
SELECT tenant_id, count_id, item_id, expected_qty, counted_qty FROM stock_count_lines
WHERE tenant_id = $1 AND count_id = $2 AND counted_qty IS NOT NULL
`

type ListCountedLinesParams struct {
	TenantID uuid.UUID
	CountID  uuid.UUID
}

// При проведении берутся только строки с внесённым фактом.
func (q *Queries) ListCountedLines(ctx context.Context, arg ListCountedLinesParams) ([]StockCountLine, error) {
	rows, err := q.db.Query(ctx, listCountedLines, arg.TenantID, arg.CountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockCountLine{}
	for rows.Next() {
		var i StockCountLine
		if err := rows.Scan(
			&i.TenantID,
			&i.CountID,
			&i.ItemID,
			&i.ExpectedQty,
			&i.CountedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyConsumption = `-- name: ListDailyConsumption :many
SELECT tenant_id, item_id, day, qty, has_data, stockout FROM daily_consumption
WHERE tenant_id = $1 AND item_id = $2 AND day >= $3
ORDER BY day
`

type ListDailyConsumptionParams struct {
	TenantID uuid.UUID
	ItemID   uuid.UUID
	Day      pgtype.Date
}

func (q *Queries) ListDailyConsumption(ctx context.Context, arg ListDailyConsumptionParams) ([]DailyConsumption, error) {
	rows, err := q.db.Query(ctx, listDailyConsumption, arg.TenantID, arg.ItemID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyConsumption{}
	for rows.Next() {
		var i DailyConsumption
		if err := rows.Scan(
			&i.TenantID,
			&i.ItemID,
			&i.Day,
			&i.Qty,
			&i.HasData,
			&i.Stockout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyConsumptionSource = `-- name: ListDailyConsumptionSource :many
SELECT
    m.item_id,
    (m.occurred_at AT TIME ZONE $3::text)::date AS day,
    (-sum(m.qty))::numeric AS qty
FROM stock_movements m
WHERE m.tenant_id = $1
  AND m.occurred_at >= $2
  AND m.type IN ('usage', 'writeoff', 'adjustment')
  AND m.reverses_id IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM stock_movements r
      WHERE r.tenant_id = m.tenant_id AND r.reverses_id = m.id
  )
GROUP BY m.item_id, day
`

type ListDailyConsumptionSourceParams struct {
	TenantID   uuid.UUID
	OccurredAt pgtype.Timestamptz
	Tz         string
}

type ListDailyConsumptionSourceRow struct {
	ItemID uuid.UUID
	Day    pgtype.Date
	Qty    decimal.Decimal
}

// Сборка дневного расхода (§4.1): расход, списания и корректировки с обратным
// знаком, в календарных днях часового пояса тенанта.
// Сторнированные движения и сами сторно из ряда исключаются.
func (q *Queries) ListDailyConsumptionSource(ctx context.Context, arg ListDailyConsumptionSourceParams) ([]ListDailyConsumptionSourceRow, error) {
	rows, err := q.db.Query(ctx, listDailyConsumptionSource, arg.TenantID, arg.OccurredAt, arg.Tz)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDailyConsumptionSourceRow{}
	for rows.Next() {
		var i ListDailyConsumptionSourceRow
		if err := rows.Scan(&i.ItemID, &i.Day, &i.Qty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDaysWithActivity = `-- name: ListDaysWithActivity :many
SELECT DISTINCT (occurred_at AT TIME ZONE $3::text)::date AS day
FROM stock_movements
WHERE tenant_id = $1
  AND occurred_at >= $2
  AND type IN ('usage', 'writeoff', 'adjustment')
`

type ListDaysWithActivityParams struct {
	TenantID   uuid.UUID
	OccurredAt pgtype.Timestamptz
	Tz         string
}

// «Нет данных ≠ ноль»: день считается «с данными», если в тенанте был хотя бы
// один расход или пересчёт (§4.1).
func (q *Queries) ListDaysWithActivity(ctx context.Context, arg ListDaysWithActivityParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listDaysWithActivity, arg.TenantID, arg.OccurredAt, arg.Tz)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var day pgtype.Date
		if err := rows.Scan(&day); err != nil {
			return nil, err
		}
		items = append(items, day)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovements = `-- name: ListMovements :many
SELECT
    m.id, m.tenant_id, m.warehouse_id, m.item_id, m.type, m.qty, m.occurred_at, m.created_at, m.created_by, m.reason, m.comment, m.order_id, m.count_id, m.reverses_id, m.idempotency_key,
    i.name  AS item_name,
    i.base_unit,
    u.name  AS author_name
FROM stock_movements m
JOIN items i     ON i.tenant_id = m.tenant_id AND i.id = m.item_id
LEFT JOIN users u ON u.tenant_id = m.tenant_id AND u.id = m.created_by
WHERE m.tenant_id = $1
  AND ($2::uuid IS NULL OR m.item_id = $2)
  AND ($3::movement_type IS NULL OR m.type = $3)
  AND ($4::uuid IS NULL OR m.created_by = $4)
  AND ($5::timestamptz IS NULL OR m.occurred_at >= $5)
  AND ($6::timestamptz IS NULL OR m.occurred_at < $6)
  AND (
      $7::timestamptz IS NULL
      OR (m.occurred_at, m.id) < ($7, $8::uuid)
  )
ORDER BY m.occurred_at DESC, m.id DESC
LIMIT $9
`

type ListMovementsParams struct {
	TenantID     uuid.UUID
	ItemID       uuid.NullUUID
	MovementType *MovementType
	AuthorID     uuid.NullUUID
	FromAt       pgtype.Timestamptz
	ToAt         pgtype.Timestamptz
	CursorAt     pgtype.Timestamptz
	CursorID     uuid.NullUUID
	RowLimit     int32
}

type ListMovementsRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	WarehouseID    uuid.UUID
	ItemID         uuid.UUID
	Type           MovementType
	Qty            decimal.Decimal
	OccurredAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	CreatedBy      uuid.NullUUID
	Reason         *string
	Comment        string
	OrderID        uuid.NullUUID
	CountID        uuid.NullUUID
	ReversesID     uuid.NullUUID
	IdempotencyKey *string
	ItemName       string
	BaseUnit       string
	AuthorName     *string
}

// Журнал с фильтрами и курсорной пагинацией (FR-11).
// Курсор — пара (occurred_at, id): id разводит движения одной секунды.
func (q *Queries) ListMovements(ctx context.Context, arg ListMovementsParams) ([]ListMovementsRow, error) {
	rows, err := q.db.Query(ctx, listMovements,
		arg.TenantID,
		arg.ItemID,
		arg.MovementType,
		arg.AuthorID,
		arg.FromAt,
		arg.ToAt,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMovementsRow{}
	for rows.Next() {
		var i ListMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WarehouseID,
			&i.ItemID,
			&i.Type,
			&i.Qty,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Reason,
			&i.Comment,
			&i.OrderID,
			&i.CountID,
			&i.ReversesID,
			&i.IdempotencyKey,
			&i.ItemName,
			&i.BaseUnit,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockCountLines = `-- name: ListStockCountLines :many
SELECT
    l.tenant_id, l.count_id, l.item_id, l.expected_qty, l.counted_qty,
    i.name AS item_name,
    i.base_unit,
    COALESCE(b.on_hand, 0)::numeric AS current_qty
FROM stock_count_lines l
JOIN items i ON i.tenant_id = l.tenant_id AND i.id = l.item_id
LEFT JOIN stock_balances b ON b.tenant_id = l.tenant_id AND b.item_id = l.item_id
WHERE l.tenant_id = $1 AND l.count_id = $2
ORDER BY i.name
`

type ListStockCountLinesParams struct {
	TenantID uuid.UUID
	CountID  uuid.UUID
}

type ListStockCountLinesRow struct {
	TenantID    uuid.UUID
	CountID     uuid.UUID
	ItemID      uuid.UUID
	ExpectedQty decimal.Decimal
	CountedQty  decimal.NullDecimal
	ItemName    string
	BaseUnit    string
	CurrentQty  decimal.Decimal
}

// Расхождение показывается до проведения: сравниваем внесённый факт
// с учётом на момент открытия документа и с текущим остатком (FR-13).
func (q *Queries) ListStockCountLines(ctx context.Context, arg ListStockCountLinesParams) ([]ListStockCountLinesRow, error) {
	rows, err := q.db.Query(ctx, listStockCountLines, arg.TenantID, arg.CountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockCountLinesRow{}
	for rows.Next() {
		var i ListStockCountLinesRow
		if err := rows.Scan(
			&i.TenantID,
			&i.CountID,
			&i.ItemID,
			&i.ExpectedQty,
			&i.CountedQty,
			&i.ItemName,
			&i.BaseUnit,
			&i.CurrentQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockCounts = `-- name: ListStockCounts :many
SELECT id, tenant_id, warehouse_id, status, scope, note, created_by, posted_by, posted_at, created_at FROM stock_counts WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListStockCountsParams struct {
	TenantID uuid.UUID
	Limit    int32
}

func (q *Queries) ListStockCounts(ctx context.Context, arg ListStockCountsParams) ([]StockCount, error) {
	rows, err := q.db.Query(ctx, listStockCounts, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockCount{}
	for rows.Next() {
		var i StockCount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WarehouseID,
			&i.Status,
			&i.Scope,
			&i.Note,
			&i.CreatedBy,
			&i.PostedBy,
			&i.PostedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBalance = `-- name: LockBalance :one
SELECT on_hand FROM stock_balances
WHERE warehouse_id = $1 AND item_id = $2
FOR UPDATE
`

type LockBalanceParams struct {
	WarehouseID uuid.UUID
	ItemID      uuid.UUID
}

// Шаг 2: блокируем строку остатка. Конкурентные списания одной позиции идут
// по очереди, поэтому проверка «не уйдём ли в минус» честная (§10.2).
func (q *Queries) LockBalance(ctx context.Context, arg LockBalanceParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, lockBalance, arg.WarehouseID, arg.ItemID)
	var on_hand decimal.Decimal
	err := row.Scan(&on_hand)
	return on_hand, err
}

const postStockCount = `-- name: PostStockCount :exec
UPDATE stock_counts SET status = 'posted', posted_at = $3, posted_by = $4
WHERE tenant_id = $1 AND id = $2
`

type PostStockCountParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	PostedAt pgtype.Timestamptz
	PostedBy uuid.NullUUID
}

func (q *Queries) PostStockCount(ctx context.Context, arg PostStockCountParams) error {
	_, err := q.db.Exec(ctx, postStockCount,
		arg.TenantID,
		arg.ID,
		arg.PostedAt,
		arg.PostedBy,
	)
	return err
}

const sumMovementsByItem = `-- name: SumMovementsByItem :many
SELECT item_id, COALESCE(sum(qty), 0)::numeric AS total
FROM stock_movements
WHERE tenant_id = $1
GROUP BY item_id
`

type SumMovementsByItemRow struct {
	ItemID uuid.UUID
	Total  decimal.Decimal
}

// Ночная сверка (FR-17): остаток обязан совпадать с суммой движений.
func (q *Queries) SumMovementsByItem(ctx context.Context, tenantID uuid.UUID) ([]SumMovementsByItemRow, error) {
	rows, err := q.db.Query(ctx, sumMovementsByItem, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumMovementsByItemRow{}
	for rows.Next() {
		var i SumMovementsByItemRow
		if err := rows.Scan(&i.ItemID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyConsumption = `-- name: UpsertDailyConsumption :exec
INSERT INTO daily_consumption (tenant_id, item_id, day, qty, has_data, stockout)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (item_id, day) DO UPDATE SET
    qty      = EXCLUDED.qty,
    has_data = EXCLUDED.has_data,
    stockout = EXCLUDED.stockout
`

type UpsertDailyConsumptionParams struct {
	TenantID uuid.UUID
	ItemID   uuid.UUID
	Day      pgtype.Date
	Qty      decimal.Decimal
	HasData  bool
	Stockout bool
}

func (q *Queries) UpsertDailyConsumption(ctx context.Context, arg UpsertDailyConsumptionParams) error {
	_, err := q.db.Exec(ctx, upsertDailyConsumption,
		arg.TenantID,
		arg.ItemID,
		arg.Day,
		arg.Qty,
		arg.HasData,
		arg.Stockout,
	)
	return err
}

const upsertStockCountLine = `-- name: UpsertStockCountLine :exec
INSERT INTO stock_count_lines (tenant_id, count_id, item_id, expected_qty, counted_qty)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (count_id, item_id) DO UPDATE SET
    expected_qty = EXCLUDED.expected_qty,
    counted_qty  = EXCLUDED.counted_qty
`

type UpsertStockCountLineParams struct {
	TenantID    uuid.UUID
	CountID     uuid.UUID
	ItemID      uuid.UUID
	ExpectedQty decimal.Decimal
	CountedQty  decimal.NullDecimal
}

func (q *Queries) UpsertStockCountLine(ctx context.Context, arg UpsertStockCountLineParams) error {
	_, err := q.db.Exec(ctx, upsertStockCountLine,
		arg.TenantID,
		arg.CountID,
		arg.ItemID,
		arg.ExpectedQty,
		arg.CountedQty,
	)
	return err
}
