// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceTenantClock = `-- name: AdvanceTenantClock :one
UPDATE tenants SET clock_offset = clock_offset + $2::interval
WHERE id = $1
RETURNING clock_offset
`

type AdvanceTenantClockParams struct {
	ID      uuid.UUID
	Column2 pgtype.Interval
}

func (q *Queries) AdvanceTenantClock(ctx context.Context, arg AdvanceTenantClockParams) (pgtype.Interval, error) {
	row := q.db.QueryRow(ctx, advanceTenantClock, arg.ID, arg.Column2)
	var clock_offset pgtype.Interval
	err := row.Scan(&clock_offset)
	return clock_offset, err
}

const countActiveSandboxes = `-- name: CountActiveSandboxes :one
SELECT count(*)::int AS active FROM tenants
WHERE is_sandbox AND (expires_at IS NULL OR expires_at > $1)
`

func (q *Queries) CountActiveSandboxes(ctx context.Context, expiresAt pgtype.Timestamptz) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveSandboxes, expiresAt)
	var active int32
	err := row.Scan(&active)
	return active, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (id, name, timezone, is_sandbox, expires_at, seed, settings)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, timezone, is_sandbox, expires_at, clock_offset, seed, autopilot, settings, created_at
`

type CreateTenantParams struct {
	ID        uuid.UUID
	Name      string
	Timezone  string
	IsSandbox bool
	ExpiresAt pgtype.Timestamptz
	Seed      int64
	Settings  []byte
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.Timezone,
		arg.IsSandbox,
		arg.ExpiresAt,
		arg.Seed,
		arg.Settings,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.IsSandbox,
		&i.ExpiresAt,
		&i.ClockOffset,
		&i.Seed,
		&i.Autopilot,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants WHERE id = $1
`

// Удаление каскадом уносит всё содержимое тенанта.
func (q *Queries) DeleteTenant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, timezone, is_sandbox, expires_at, clock_offset, seed, autopilot, settings, created_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.IsSandbox,
		&i.ExpiresAt,
		&i.ClockOffset,
		&i.Seed,
		&i.Autopilot,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveTenants = `-- name: ListActiveTenants :many
SELECT id, name, timezone, is_sandbox, expires_at, clock_offset, seed, autopilot, settings, created_at FROM tenants
WHERE expires_at IS NULL OR expires_at > $1
ORDER BY created_at
`

// Обход тенантов ночными задачами. Истёкшие песочницы пропускаются:
// их всё равно вот-вот удалит очистка.
func (q *Queries) ListActiveTenants(ctx context.Context, expiresAt pgtype.Timestamptz) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listActiveTenants, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Timezone,
			&i.IsSandbox,
			&i.ExpiresAt,
			&i.ClockOffset,
			&i.Seed,
			&i.Autopilot,
			&i.Settings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredSandboxes = `-- name: ListExpiredSandboxes :many
SELECT id FROM tenants
WHERE is_sandbox AND expires_at IS NOT NULL AND expires_at <= $1
ORDER BY expires_at
LIMIT $2
`

type ListExpiredSandboxesParams struct {
	ExpiresAt pgtype.Timestamptz
	Limit     int32
}

// Очистка песочниц: раз в час, пачками, чтобы не блокировать БД (§7.5).
func (q *Queries) ListExpiredSandboxes(ctx context.Context, arg ListExpiredSandboxesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listExpiredSandboxes, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetTenantClock = `-- name: ResetTenantClock :exec
UPDATE tenants SET clock_offset = '0' WHERE id = $1
`

func (q *Queries) ResetTenantClock(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetTenantClock, id)
	return err
}

const setTenantAutopilot = `-- name: SetTenantAutopilot :exec
UPDATE tenants SET autopilot = $2 WHERE id = $1
`

type SetTenantAutopilotParams struct {
	ID        uuid.UUID
	Autopilot bool
}

func (q *Queries) SetTenantAutopilot(ctx context.Context, arg SetTenantAutopilotParams) error {
	_, err := q.db.Exec(ctx, setTenantAutopilot, arg.ID, arg.Autopilot)
	return err
}

const updateTenantSettings = `-- name: UpdateTenantSettings :exec
UPDATE tenants SET settings = $2 WHERE id = $1
`

type UpdateTenantSettingsParams struct {
	ID       uuid.UUID
	Settings []byte
}

func (q *Queries) UpdateTenantSettings(ctx context.Context, arg UpdateTenantSettingsParams) error {
	_, err := q.db.Exec(ctx, updateTenantSettings, arg.ID, arg.Settings)
	return err
}
